// This file is auto-generated by @hey-api/openapi-ts

export { getPing, type Options, postPing } from './sdk.gen';
export type { ClientOptions, GetPingData, GetPingError, GetPingErrors, GetPingResponse, GetPingResponses, PostPingData, PostPingResponse, PostPingResponses } from './types.gen';
