// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetPingData, GetPingErrors, GetPingResponses, PostPingData, PostPingResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getPing = <ThrowOnError extends boolean = false>(options?: Options<GetPingData, ThrowOnError>): RequestResult<GetPingResponses, GetPingErrors, ThrowOnError> => (options?.client ?? client).get<GetPingResponses, GetPingErrors, ThrowOnError>({ url: '/ping', ...options });

export const postPing = <ThrowOnError extends boolean = false>(options: Options<PostPingData, ThrowOnError>): RequestResult<PostPingResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostPingResponses, unknown, ThrowOnError>({
  url: '/ping',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});
