// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type MockItem = (({
  kind: 'FOO';
} & FooItem) | ({
  kind: 'BAR';
} & BarItem)) & {
  id: string;
  kind: string;
};

export type FooItem = {
  foo: string;
};

export type BarItem = {
  bar: string;
};
