// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod/v3';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { PostFooData } from './types.gen';
import { zPostFooResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

const postFooResponseTransformer = async (data: unknown) => await zPostFooResponse.parseAsync(data);

type PostFooTransformedResponses = {
  200: Awaited<ReturnType<typeof postFooResponseTransformer>>;
};

export type PostFooTransformedResponse = PostFooTransformedResponses[keyof PostFooTransformedResponses];

export const postFoo = <ThrowOnError extends boolean = false>(options?: Options<PostFooData, ThrowOnError>): RequestResult<PostFooTransformedResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostFooTransformedResponses, unknown, ThrowOnError>({
  requestValidator: async (data) => await z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
  }).parseAsync(data),
  responseTransformer: postFooResponseTransformer,
  url: '/foo',
  ...options
});
