// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/v4-mini';

export const zFoo = z.strictObject({
  foo: z.string()
});

export const zBar = z.intersection(zFoo, z.object({}));

export const zBaz = z.intersection(zFoo, z.strictObject({
  bar: z.string()
}));
