// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zRecord = z.object({
  name: z.string().optional().default('anonymous'),
  items: z.array(z.string()).optional().default([])
});

/**
 * Status text
 */
export const zGetStatusResponse = z.string();

/**
 * Records deleted
 */
export const zDeleteRecordsResponse = z.void();

export const zGetRecordsResponse = z.union([
  zRecord.and(z.object({
    kind: z.literal('existing')
  })),
  zRecord.and(z.object({
    kind: z.literal('created')
  }))
]);
