# This file is auto-generated by @hey-api/openapi-python

from pydantic import BaseModel, Field, RootModel


class Thing(BaseModel):
    id: str
    count: int


class Widget(BaseModel):
    id: str
    status: str


class NotFoundProblem(BaseModel):
    code: str
    message: str


class ServerProblem(BaseModel):
    code: str
    trace_id: str = Field(..., alias="traceId")


class ListThingsResponse(RootModel[Thing]):
    """OK"""

    root: Thing


class GetThingResponse(RootModel[Thing]):
    """OK"""

    root: Thing


class CreateWidgetResponse(RootModel[Widget]):
    """Created"""

    root: Widget
