# This file is auto-generated by @hey-api/openapi-python

from functools import cached_property

from .client import Client


class Gadgets(Client):
    def list(self):
        """List Widget Gadgets"""

        return self.client.get("/v1/widgets/gadgets")


class Widgets(Client):
    @cached_property
    def gadgets(self) -> Gadgets:
        return Gadgets(client=self.client)


class Sdk(Client):
    def widgets(self):
        """List Widgets"""

        return self.client.get("/v1/widgets")

    @cached_property
    def widgets2(self) -> Widgets:
        return Widgets(client=self.client)
