// This file is auto-generated by @hey-api/openapi-ts

import type { DefaultError, UseMutationOptions } from '@tanstack/react-query';

import { type Options, postFoo, type PostFooTransformedResponse } from '../sdk.gen';
import type { PostFooData } from '../types.gen';

export const postFooMutation = (options?: Partial<Options<PostFooData>>): UseMutationOptions<PostFooTransformedResponse, DefaultError, Options<PostFooData>> => {
  const mutationOptions: UseMutationOptions<PostFooTransformedResponse, DefaultError, Options<PostFooData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postFoo({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    }
  };
  return mutationOptions;
};
