# This file is auto-generated by @hey-api/openapi-python

from pydantic import BaseModel, RootModel


class Widget(BaseModel):
    name: str


class CreateWidgetBody(RootModel[Widget]):
    root: Widget


class CreateWidgetSprocket(BaseModel):
    url: str


class CreateWidget(BaseModel):
    sprocket: CreateWidgetSprocket


class CreateWidgetResponse(CreateWidget, Widget):
    """Created"""

    pass
