// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';

export const PetCreatedWebhookRequestSchema = Schema.Struct({
  body: Schema.Struct({
    id: Schema.Number.check(Schema.isInt())
  }),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});
