// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Webhooks = PetCreatedWebhookRequest;

export type PetCreatedWebhookPayload = {
  id: number;
};

export type PetCreatedWebhookRequest = {
  body: PetCreatedWebhookPayload;
  key: 'petCreated';
  path?: never;
  query?: never;
};
