# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel


class ListWidgetsQuery(BaseModel):
    status: Optional[str] = None


class GetWidgetReservedNamesQuery(BaseModel):
    auth: Optional[str] = None
    security: Optional[str] = None
