# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client


class Sdk(Client):
    def list_widgets(self, status: Optional[str] = None):
        params = build_client_params([{"in": "query", "key": "status"}], [{"type": "http", "scheme": "bearer"}], self.auth, status=status)
        return self.request_options("get", "/widgets", params)

    def get_widget_basic(self):
        params = build_client_params([], [{"type": "http", "scheme": "basic"}], self.auth)
        return self.request_options("get", "/widgets/basic", params)

    def get_widget_header_key(self):
        params = build_client_params([], [{"type": "apiKey", "name": "X-Api-Key"}], self.auth)
        return self.request_options("get", "/widgets/header-key", params)

    def get_widget_query_key(self):
        params = build_client_params([], [{"type": "apiKey", "in": "query", "name": "api_key"}], self.auth)
        return self.request_options("get", "/widgets/query-key", params)

    def get_widget_cookie_key(self):
        params = build_client_params([], [{"type": "apiKey", "in": "cookie", "name": "session_id"}], self.auth)
        return self.request_options("get", "/widgets/cookie-key", params)

    def get_widget_public(self):
        return self.client.get("/widgets/public")

    def get_widget_reserved_names(self, auth: Optional[str] = None, security: Optional[str] = None):
        params = build_client_params([{"in": "query", "key": "auth"}, {"in": "query", "key": "security"}], [{"type": "http", "scheme": "bearer"}], self.auth, auth=auth, security=security)
        return self.request_options("get", "/widgets/reserved-names", params)

    def create_widget(self):
        params = build_client_params([], [{"type": "http", "scheme": "bearer"}], self.auth)
        return self.request_options("post", "/widgets/no-params", params)
