# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client


class Sdk(Client):
    def list_widgets(self, status: Optional[str] = None):
        params = build_client_params([{"in": "query", "key": "status"}], status=status, security=[{"type": "http", "scheme": "bearer"}], auth=self.auth)
        return self.request_options("get", "/widgets", params)

    def get_widget_basic(self):
        params = build_client_params([], security=[{"type": "http", "scheme": "basic"}], auth=self.auth)
        return self.request_options("get", "/widgets/basic", params)

    def get_widget_header_key(self):
        params = build_client_params([], security=[{"type": "apiKey", "name": "X-Api-Key"}], auth=self.auth)
        return self.request_options("get", "/widgets/header-key", params)

    def get_widget_query_key(self):
        params = build_client_params([], security=[{"type": "apiKey", "in": "query", "name": "api_key"}], auth=self.auth)
        return self.request_options("get", "/widgets/query-key", params)

    def get_widget_cookie_key(self):
        params = build_client_params([], security=[{"type": "apiKey", "in": "cookie", "name": "session_id"}], auth=self.auth)
        return self.request_options("get", "/widgets/cookie-key", params)

    def get_widget_public(self):
        return self.client.get("/widgets/public")

    def create_widget(self):
        params = build_client_params([], security=[{"type": "http", "scheme": "bearer"}], auth=self.auth)
        return self.request_options("post", "/widgets/no-params", params)
