# This file is auto-generated by @hey-api/openapi-python

from datetime import datetime
from typing import Any, TypeAlias, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class UserNotificationDeleteContentBase(BaseModel):
    name: str


class UserNotificationDeleteContentError_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    finished_at: datetime = Field(..., alias="finishedAt")
    error: str


UserNotificationDeleteContentError: TypeAlias = Any


class UserNotificationDeleteContentRunning_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    started_at: datetime = Field(..., alias="startedAt")


UserNotificationDeleteContentRunning: TypeAlias = Any


class UserNotificationDeleteContentSuccess_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    finished_at: datetime = Field(..., alias="finishedAt")


UserNotificationDeleteContentSuccess: TypeAlias = Any


class UserNotificationDeleteContent(RootModel[Union[UserNotificationDeleteContentRunning, UserNotificationDeleteContentSuccess, UserNotificationDeleteContentError]]):
    root: Union[UserNotificationDeleteContentRunning, UserNotificationDeleteContentSuccess, UserNotificationDeleteContentError]


class GetNotificationResponse(RootModel[UserNotificationDeleteContent]):
    """success"""

    root: UserNotificationDeleteContent
