# This file is auto-generated by @hey-api/openapi-python

from datetime import datetime
from typing import Union

from pydantic import BaseModel, Field, RootModel


class UserNotificationDeleteContentBase(BaseModel):
    name: str


class UserNotificationDeleteContentError_(BaseModel):
    finished_at: datetime = Field(..., alias="finishedAt")
    error: str


class UserNotificationDeleteContentError(UserNotificationDeleteContentError_, UserNotificationDeleteContentBase):
    pass


class UserNotificationDeleteContentRunning_(BaseModel):
    started_at: datetime = Field(..., alias="startedAt")


class UserNotificationDeleteContentRunning(UserNotificationDeleteContentRunning_, UserNotificationDeleteContentBase):
    pass


class UserNotificationDeleteContentSuccess_(BaseModel):
    finished_at: datetime = Field(..., alias="finishedAt")


class UserNotificationDeleteContentSuccess(UserNotificationDeleteContentSuccess_, UserNotificationDeleteContentBase):
    pass


class UserNotificationDeleteContent(RootModel[Union[UserNotificationDeleteContentRunning, UserNotificationDeleteContentSuccess, UserNotificationDeleteContentError]]):
    root: Union[UserNotificationDeleteContentRunning, UserNotificationDeleteContentSuccess, UserNotificationDeleteContentError]


class GetNotificationResponse(RootModel[UserNotificationDeleteContent]):
    """success"""

    root: UserNotificationDeleteContent
