// This file is auto-generated by @hey-api/openapi-ts

import { oc } from '@orpc/contract';
import * as v from 'valibot';

import { vGetItemPath, vGetItemResponse, vInvalidItemId, vItemNotFound } from './valibot.gen';

export const getItem = oc.route({
  inputStructure: 'detailed',
  method: 'GET',
  operationId: 'getItem',
  path: '/items/{itemId}',
  tags: ['default']
}).errors({ BAD_REQUEST: { data: vInvalidItemId, message: 'Invalid item ID' }, NOT_FOUND: { data: vItemNotFound, message: 'Item not found' } }).input(v.object({ params: vGetItemPath })).output(vGetItemResponse);

export const contract = {
  getItem
};
