// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vInvalidItemId = v.object({
  reason: v.string()
});

export const vItemNotFound = v.object({
  itemId: v.string()
});

export const vGetItemPath = v.object({
  itemId: v.string()
});

/**
 * Item found
 */
export const vGetItemResponse = v.object({
  id: v.string()
});
