# This file is auto-generated by @hey-api/openapi-python

from typing import Annotated, Any, Literal, TypeAlias, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AnimalPayload(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type_discriminator: str = Field(..., alias="typeDiscriminator")


class DogPayload_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    breed: str
    can_fetch: bool = Field(..., alias="canFetch")
    display_breed: str = Field(..., alias="displayBreed")
    type_discriminator: Literal["dog"] = Field(..., alias="typeDiscriminator")


DogPayload: TypeAlias = Any


class CatPayload_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    breed: str
    lives_remaining: int = Field(..., alias="livesRemaining")
    display_breed: str = Field(..., alias="displayBreed")
    type_discriminator: Literal["cat"] = Field(..., alias="typeDiscriminator")


CatPayload: TypeAlias = Any


class CreatePetRequest(BaseModel):
    name: str
    animal: Annotated[Union[DogPayload, CatPayload], Field(discriminator="typeDiscriminator")]


class CreatePetResponse(BaseModel):
    id: str
    name: str
    animal: Annotated[Union[DogPayload, CatPayload], Field(discriminator="typeDiscriminator")]


class AnimalPayloadWritable(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type_discriminator: str = Field(..., alias="typeDiscriminator")


class DogPayloadWritable_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    breed: str
    can_fetch: bool = Field(..., alias="canFetch")
    type_discriminator: Literal["dog"] = Field(..., alias="typeDiscriminator")


DogPayloadWritable: TypeAlias = Any


class CatPayloadWritable_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    breed: str
    lives_remaining: int = Field(..., alias="livesRemaining")
    type_discriminator: Literal["cat"] = Field(..., alias="typeDiscriminator")


CatPayloadWritable: TypeAlias = Any


class CreatePetRequestWritable(BaseModel):
    name: str
    animal: Annotated[Union[DogPayloadWritable, CatPayloadWritable], Field(discriminator="typeDiscriminator")]


class CreatePetResponseWritable(BaseModel):
    id: str
    name: str
    animal: Annotated[Union[DogPayloadWritable, CatPayloadWritable], Field(discriminator="typeDiscriminator")]


class PostPetsBody(RootModel[CreatePetRequestWritable]):
    root: CreatePetRequestWritable


class PostPetsResponse(RootModel[CreatePetResponse]):
    """OK"""

    root: CreatePetResponse
