// This file is auto-generated by @hey-api/openapi-ts

export type { ClientOptions, GetPingData, GetPingError, GetPingErrors, GetPingResponse, GetPingResponses, Operations, PostPingData, PostPingResponse, PostPingResponses } from './types.gen';
