# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, Field, RootModel


class Thing(BaseModel):
    """A property name that cannot start a Python identifier, alongside the names that are already handled, so the two stay visible together."""

    field_2fa: Optional[str] = Field(default=None, alias="2fa")
    field_3d: Optional[str] = Field(default=None, alias="3d")
    class_: Optional[str] = Field(default=None, alias="class")
    internal: Optional[str] = Field(default=None, alias="_internal")
    some_name: Optional[str] = Field(default=None, alias="some-name")
    plain: str


class ListThingsResponse(RootModel[Thing]):
    """OK"""

    root: Thing
