// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type FooItem = {
  fooValue: string;
};

export type BarItem = {
  barValue: number;
};

export type MockItem = (({
  kind: 'FOO';
} & FooItem) | ({
  kind: 'BAR';
} & BarItem)) & {
  kind: string;
  id: string;
};

export type GetMockItemsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/mock/items';
};

export type GetMockItemsResponses = {
  /**
   * OK
   */
  200: {
    items: Array<MockItem>;
  };
};

export type GetMockItemsResponse = GetMockItemsResponses[keyof GetMockItemsResponses];
