// This file is auto-generated by @hey-api/openapi-ts

import { oc } from '@orpc/contract';
import * as z from 'zod';

import { zGetItemPath, zGetItemResponse, zInvalidItemId, zItemNotFound } from './zod.gen';

export const getItem = oc.route({
  inputStructure: 'detailed',
  method: 'GET',
  operationId: 'getItem',
  path: '/items/{itemId}',
  tags: ['default']
}).errors({ BAD_REQUEST: { data: zInvalidItemId, message: 'Invalid item ID' }, NOT_FOUND: { data: zItemNotFound, message: 'Item not found' } }).input(z.object({ params: zGetItemPath })).output(zGetItemResponse);

export const contract = {
  getItem
};
