// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zInvalidItemId = z.object({
  reason: z.string()
});

export const zItemNotFound = z.object({
  itemId: z.string()
});

export const zGetItemPath = z.object({
  itemId: z.string()
});

/**
 * Item found
 */
export const zGetItemResponse = z.object({
  id: z.string()
});
