// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

/**
 * Model with number-only name
 */
export const z400 = z.components_schemas_400();

/**
 * Testing multiline comments in string: First line
 * Second line
 *
 * Fourth line
 */
export const zCamelCaseCommentWithBreaks = z.components_schemas_camelCaseCommentWithBreaks();

/**
 * Testing multiline comments in string: First line
 * Second line
 *
 * Fourth line
 */
export const zCommentWithBreaks = z.components_schemas_CommentWithBreaks();

/**
 * Testing backticks in string: `backticks` and ```multiple backticks``` should work
 */
export const zCommentWithBackticks = z.components_schemas_CommentWithBackticks();

/**
 * Testing backticks and quotes in string: `backticks`, 'quotes', "double quotes" and ```multiple backticks``` should work
 */
export const zCommentWithBackticksAndQuotes = z.components_schemas_CommentWithBackticksAndQuotes();

/**
 * Testing slashes in string: \backwards\\\ and /forwards/// should work
 */
export const zCommentWithSlashes = z.components_schemas_CommentWithSlashes();

/**
 * Testing expression placeholders in string: ${expression} should work
 */
export const zCommentWithExpressionPlaceholders = z.components_schemas_CommentWithExpressionPlaceholders();

/**
 * Testing quotes in string: 'single quote''' and "double quotes""" should work
 */
export const zCommentWithQuotes = z.components_schemas_CommentWithQuotes();

/**
 * Testing reserved characters in string: * inline * and ** inline ** should work
 */
export const zCommentWithReservedCharacters = z.components_schemas_CommentWithReservedCharacters();

/**
 * This is a simple number
 */
export const zSimpleInteger = z.components_schemas_SimpleInteger();

/**
 * This is a simple boolean
 */
export const zSimpleBoolean = z.components_schemas_SimpleBoolean();

/**
 * This is a simple string
 */
export const zSimpleString = z.components_schemas_SimpleString();

/**
 * A string with non-ascii (unicode) characters valid in typescript identifiers (æøåÆØÅöÔèÈ字符串)
 */
export const zNonAsciiStringæøåÆøÅöôêÊ字符串 = z.components_schemas_NonAsciiStringæøåÆØÅöôêÊ字符串();

/**
 * This is a simple file
 */
export const zSimpleFile = z.components_schemas_SimpleFile();

/**
 * This is a simple string
 */
export const zSimpleStringWithPattern = z.nullable(z.components_schemas_SimpleStringWithPattern());

/**
 * This is a simple enum with strings
 */
export const zEnumWithStrings = z.components_schemas_EnumWithStrings();

export const zEnumWithReplacedCharacters = z.components_schemas_EnumWithReplacedCharacters();

/**
 * This is a simple enum with numbers
 */
export const zEnumWithNumbers = z._default(z.components_schemas_EnumWithNumbers(), 200);

/**
 * Success=1,Warning=2,Error=3
 */
export const zEnumFromDescription = z.components_schemas_EnumFromDescription();

/**
 * This is a simple enum with numbers
 */
export const zEnumWithExtensions = z.components_schemas_EnumWithExtensions();

export const zEnumWithXEnumNames = z.components_schemas_EnumWithXEnumNames();

/**
 * This is a simple array with numbers
 */
export const zArrayWithNumbers = z.components_schemas_ArrayWithNumbers();

/**
 * This is a simple array with booleans
 */
export const zArrayWithBooleans = z.components_schemas_ArrayWithBooleans();

/**
 * This is a simple array with strings
 */
export const zArrayWithStrings = z._default(z.components_schemas_ArrayWithStrings(), ['test']);

/**
 * This is a simple array with properties
 */
export const zArrayWithProperties = z.components_schemas_ArrayWithProperties();

/**
 * This is a simple array with any of properties
 */
export const zArrayWithAnyOfProperties = z.components_schemas_ArrayWithAnyOfProperties();

export const zAnyOfAnyAndNull = z.components_schemas_AnyOfAnyAndNull();

/**
 * This is a simple array with any of properties
 */
export const zAnyOfArrays = z.components_schemas_AnyOfArrays();

/**
 * This is a string dictionary
 */
export const zDictionaryWithString = z.components_schemas_DictionaryWithString();

export const zDictionaryWithPropertiesAndAdditionalProperties = z.components_schemas_DictionaryWithPropertiesAndAdditionalProperties();

/**
 * This is a string dictionary
 */
export const zDictionaryWithDictionary = z.components_schemas_DictionaryWithDictionary();

/**
 * This is a complex dictionary
 */
export const zDictionaryWithProperties = z.components_schemas_DictionaryWithProperties();

/**
 * This is a model with one number property
 */
export const zModelWithInteger = z.components_schemas_ModelWithInteger();

/**
 * This is a model with one boolean property
 */
export const zModelWithBoolean = z.components_schemas_ModelWithBoolean();

/**
 * This is a model with one string property
 */
export const zModelWithString = z.components_schemas_ModelWithString();

/**
 * This is a simple reference
 */
export const zSimpleReference = zModelWithString;

/**
 * This is a simple array with references
 */
export const zArrayWithReferences = z.components_schemas_ArrayWithReferences();

/**
 * This is a simple array containing an array
 */
export const zArrayWithArray = z.components_schemas_ArrayWithArray();

/**
 * This is a string reference
 */
export const zDictionaryWithReference = z.components_schemas_DictionaryWithReference();

/**
 * This is a complex dictionary
 */
export const zDictionaryWithArray = z.components_schemas_DictionaryWithArray();

/**
 * This is a model with one string property
 */
export const zModelWithStringError = z.components_schemas_ModelWithStringError();

/**
 * `Comment` or `VoiceComment`. The JSON object for adding voice comments to tickets is different. See [Adding voice comments to tickets](/documentation/ticketing/managing-tickets/adding-voice-comments-to-tickets)
 */
export const zModelFromZendesk = z['components_schemas_Model-From.Zendesk']();

/**
 * This is a model with one string property
 */
export const zModelWithNullableString = z.components_schemas_ModelWithNullableString();

/**
 * This is a model with one enum
 */
export const zModelWithEnum = z.components_schemas_ModelWithEnum();

/**
 * This is a model with one enum with escaped name
 */
export const zModelWithEnumWithHyphen = z.components_schemas_ModelWithEnumWithHyphen();

/**
 * This is a model with one enum
 */
export const zModelWithEnumFromDescription = z.components_schemas_ModelWithEnumFromDescription();

/**
 * This is a model with nested enums
 */
export const zModelWithNestedEnums = z.components_schemas_ModelWithNestedEnums();

/**
 * This is a model with one property containing an array
 */
export const zModelWithArray = z.components_schemas_ModelWithArray();

/**
 * This is a model with one property containing a dictionary
 */
export const zModelWithDictionary = z.components_schemas_ModelWithDictionary();

/**
 * This is a deprecated model with a deprecated property
 *
 * @deprecated
 */
export const zDeprecatedModel = z.components_schemas_DeprecatedModel();

/**
 * This is a model with one property containing a circular reference
 */
export const zModelWithCircularReference = z.components_schemas_ModelWithCircularReference();

/**
 * This is a model with one property with a 'one of' relationship
 */
export const zCompositionWithOneOf = z.components_schemas_CompositionWithOneOf();

/**
 * This is a model with one property with a 'one of' relationship where the options are not $ref
 */
export const zCompositionWithOneOfAnonymous = z.components_schemas_CompositionWithOneOfAnonymous();

/**
 * Circle
 */
export const zModelCircle = z.components_schemas_ModelCircle();

/**
 * Square
 */
export const zModelSquare = z.components_schemas_ModelSquare();

/**
 * This is a model with one property with a 'one of' relationship where the options are not $ref
 */
export const zCompositionWithOneOfDiscriminator = z.components_schemas_CompositionWithOneOfDiscriminator();

/**
 * This is a model with one property with a 'any of' relationship
 */
export const zCompositionWithAnyOf = z.components_schemas_CompositionWithAnyOf();

/**
 * This is a model with one property with a 'any of' relationship where the options are not $ref
 */
export const zCompositionWithAnyOfAnonymous = z.components_schemas_CompositionWithAnyOfAnonymous();

/**
 * This is a model with nested 'any of' property with a type null
 */
export const zCompositionWithNestedAnyAndTypeNull = z.components_schemas_CompositionWithNestedAnyAndTypeNull();

export const z3eNum1Период = z['components_schemas_3e-num_1Период']();

export const zConstValue = z.components_schemas_ConstValue();

/**
 * This is a model with one property with a 'any of' relationship where the options are not $ref
 */
export const zCompositionWithNestedAnyOfAndNull = z.components_schemas_CompositionWithNestedAnyOfAndNull();

/**
 * This is a model with one property with a 'one of' relationship
 */
export const zCompositionWithOneOfAndNullable = z.components_schemas_CompositionWithOneOfAndNullable();

/**
 * This is a model that contains a simple dictionary within composition
 */
export const zCompositionWithOneOfAndSimpleDictionary = z.components_schemas_CompositionWithOneOfAndSimpleDictionary();

/**
 * This is a model that contains a dictionary of simple arrays within composition
 */
export const zCompositionWithOneOfAndSimpleArrayDictionary = z.components_schemas_CompositionWithOneOfAndSimpleArrayDictionary();

/**
 * This is a model that contains a dictionary of complex arrays (composited) within composition
 */
export const zCompositionWithOneOfAndComplexArrayDictionary = z.components_schemas_CompositionWithOneOfAndComplexArrayDictionary();

/**
 * This is a model with one property with a 'all of' relationship
 */
export const zCompositionWithAllOfAndNullable = z.components_schemas_CompositionWithAllOfAndNullable();

/**
 * This is a model with one property with a 'any of' relationship
 */
export const zCompositionWithAnyOfAndNullable = z.components_schemas_CompositionWithAnyOfAndNullable();

/**
 * This is a base model with two simple optional properties
 */
export const zCompositionBaseModel = z.components_schemas_CompositionBaseModel();

/**
 * This is a model that extends the base model
 */
export const zCompositionExtendedModel = z.components_schemas_CompositionExtendedModel();

/**
 * This is a model with one nested property
 */
export const zModelWithProperties = z.components_schemas_ModelWithProperties();

/**
 * This is a model with one property containing a reference
 */
export const zModelWithReference = z.components_schemas_ModelWithReference();

/**
 * This is a model with one nested property
 */
export const zModelWithNestedProperties = z.components_schemas_ModelWithNestedProperties();

/**
 * This is a model with duplicated properties
 */
export const zModelWithDuplicateProperties = z.components_schemas_ModelWithDuplicateProperties();

/**
 * This is a model with ordered properties
 */
export const zModelWithOrderedProperties = z.components_schemas_ModelWithOrderedProperties();

/**
 * This is a model with duplicated imports
 */
export const zModelWithDuplicateImports = z.components_schemas_ModelWithDuplicateImports();

/**
 * This is a model that extends another model
 */
export const zModelThatExtends = z.components_schemas_ModelThatExtends();

/**
 * This is a model that extends another model
 */
export const zModelThatExtendsExtends = z.components_schemas_ModelThatExtendsExtends();

/**
 * This is a model that contains a some patterns
 */
export const zModelWithPattern = z.components_schemas_ModelWithPattern();

export const zFile = z.components_schemas_File();

export const zDefault = z.components_schemas_default();

export const zPageable = z.components_schemas_Pageable();

/**
 * This is a free-form object without additionalProperties.
 */
export const zFreeFormObjectWithoutAdditionalProperties = z.components_schemas_FreeFormObjectWithoutAdditionalProperties();

/**
 * This is a free-form object with additionalProperties: true.
 */
export const zFreeFormObjectWithAdditionalPropertiesEqTrue = z.components_schemas_FreeFormObjectWithAdditionalPropertiesEqTrue();

/**
 * This is a free-form object with additionalProperties: {}.
 */
export const zFreeFormObjectWithAdditionalPropertiesEqEmptyObject = z.components_schemas_FreeFormObjectWithAdditionalPropertiesEqEmptyObject();

export const zModelWithConst = z.components_schemas_ModelWithConst();

/**
 * This is a model with one property and additionalProperties: true
 */
export const zModelWithAdditionalPropertiesEqTrue = z.components_schemas_ModelWithAdditionalPropertiesEqTrue();

export const zNestedAnyOfArraysNullable = z.components_schemas_NestedAnyOfArraysNullable();

/**
 * An object that can be null
 */
export const zNullableObject = z._default(z.nullable(z.components_schemas_NullableObject()), null);

/**
 * Some % character
 */
export const zCharactersInDescription = z.components_schemas_CharactersInDescription();

export const zModelWithNullableObject = z.components_schemas_ModelWithNullableObject();

/**
 * An object with additional properties that can be null (anyOf ref + null)
 */
export const zModelWithAdditionalPropertiesRef = z.components_schemas_ModelWithAdditionalPropertiesRef();

export const zModelWithOneOfEnum = z.components_schemas_ModelWithOneOfEnum();

export const zModelWithNestedArrayEnumsDataFoo = z.components_schemas_ModelWithNestedArrayEnumsDataFoo();

export const zModelWithNestedArrayEnumsDataBar = z.components_schemas_ModelWithNestedArrayEnumsDataBar();

export const zModelWithNestedArrayEnumsData = z.components_schemas_ModelWithNestedArrayEnumsData();

export const zModelWithNestedArrayEnums = z.components_schemas_ModelWithNestedArrayEnums();

export const zModelWithNestedCompositionEnums = z.components_schemas_ModelWithNestedCompositionEnums();

export const zModelWithReadOnlyAndWriteOnly = z.components_schemas_ModelWithReadOnlyAndWriteOnly();

/**
 * This is a model with one property containing an array
 */
export const zModelWithArrayReadOnlyAndWriteOnly = z.components_schemas_ModelWithArrayReadOnlyAndWriteOnly();

export const zModelWithConstantSizeArray = z.components_schemas_ModelWithConstantSizeArray();

export const zModelWithAnyOfConstantSizeArray = z.components_schemas_ModelWithAnyOfConstantSizeArray();

export const zModelWithPrefixItemsConstantSizeArray = z.components_schemas_ModelWithPrefixItemsConstantSizeArray();

export const zModelWithAnyOfConstantSizeArrayNullable = z.components_schemas_ModelWithAnyOfConstantSizeArrayNullable();

export const zModelWithAnyOfConstantSizeArrayAndIntersect = z.components_schemas_ModelWithAnyOfConstantSizeArrayAndIntersect();

export const zModelWithNumericEnumUnion = z.components_schemas_ModelWithNumericEnumUnion();

/**
 * Some description with `back ticks`
 */
export const zModelWithBackticksInDescription = z.components_schemas_ModelWithBackticksInDescription();

/**
 * Model used to test deduplication strategy (unused)
 */
export const zParameterSimpleParameterUnused = z.components_schemas_ParameterSimpleParameterUnused();

/**
 * Model used to test deduplication strategy
 */
export const zPostServiceWithEmptyTagResponse = z.components_schemas_PostServiceWithEmptyTagResponse();

/**
 * Model used to test deduplication strategy
 */
export const zPostServiceWithEmptyTagResponse2 = z.components_schemas_PostServiceWithEmptyTagResponse2();

/**
 * Model used to test deduplication strategy
 */
export const zDeleteFooData = z.components_schemas_DeleteFooData();

/**
 * Model used to test deduplication strategy
 */
export const zDeleteFooData2 = z.components_schemas_DeleteFooData2();

/**
 * Model with restricted keyword name
 */
export const zImport = z.components_schemas_import();

export const zModelWithAnyOfConstantSizeArrayWithNSizeAndOptions = z.components_schemas_ModelWithAnyOfConstantSizeArrayWithNSizeAndOptions();

export const zSchemaWithFormRestrictedKeys = z.components_schemas_SchemaWithFormRestrictedKeys();

/**
 * This schema was giving PascalCase transformations a hard time
 */
export const zIoK8sApimachineryPkgApisMetaV1Preconditions = z['components_schemas_io.k8s.apimachinery.pkg.apis.meta.v1.Preconditions']();

/**
 * This schema was giving PascalCase transformations a hard time
 */
export const zIoK8sApimachineryPkgApisMetaV1DeleteOptions = z['components_schemas_io.k8s.apimachinery.pkg.apis.meta.v1.DeleteOptions']();

export const zAdditionalPropertiesUnknownIssue = z.components_schemas_AdditionalPropertiesUnknownIssue();

export const zAdditionalPropertiesUnknownIssue2 = z.components_schemas_AdditionalPropertiesUnknownIssue2();

export const zAdditionalPropertiesUnknownIssue3 = z.components_schemas_AdditionalPropertiesUnknownIssue3();

export const zAdditionalPropertiesIntegerIssue = z.components_schemas_AdditionalPropertiesIntegerIssue();

export const zGenericSchemaDuplicateIssue1SystemBoolean = z['components_schemas_Generic.Schema.Duplicate.Issue`1[System.Boolean]']();

export const zGenericSchemaDuplicateIssue1SystemString = z['components_schemas_Generic.Schema.Duplicate.Issue`1[System.String]']();

export const zOneOfAllOfIssue = z.components_schemas_OneOfAllOfIssue();

export const zExternalSharedModel = z.components_schemas_ExternalSharedModel();

/**
 * External ref to shared model (A)
 */
export const zExternalRefA = zExternalSharedModel;

/**
 * External ref to shared model (B)
 */
export const zExternalRefB = zExternalSharedModel;

/**
 * This is a model with one nested property
 */
export const zModelWithPropertiesWritable = z.components_schemas_ModelWithPropertiesWritable();

/**
 * This is a model with one property containing a reference
 */
export const zModelWithReferenceWritable = z.components_schemas_ModelWithReferenceWritable();

/**
 * This is a model that contains a some patterns
 */
export const zModelWithPatternWritable = z.components_schemas_ModelWithPatternWritable();

export const zFileWritable = z.components_schemas_FileWritable();

export const zModelWithReadOnlyAndWriteOnlyWritable = z.components_schemas_ModelWithReadOnlyAndWriteOnlyWritable();

/**
 * This is a model with one property containing an array
 */
export const zModelWithArrayReadOnlyAndWriteOnlyWritable = z.components_schemas_ModelWithArrayReadOnlyAndWriteOnlyWritable();

export const zModelWithAnyOfConstantSizeArrayWithNSizeAndOptionsWritable = z.components_schemas_ModelWithAnyOfConstantSizeArrayWithNSizeAndOptionsWritable();

export const zAdditionalPropertiesUnknownIssueWritable = z.components_schemas_AdditionalPropertiesUnknownIssueWritable();

export const zGenericSchemaDuplicateIssue1SystemBooleanWritable = z['components_schemas_Generic.Schema.Duplicate.Issue`1[System.Boolean]Writable']();

export const zGenericSchemaDuplicateIssue1SystemStringWritable = z['components_schemas_Generic.Schema.Duplicate.Issue`1[System.String]Writable']();

export const zOneOfAllOfIssueWritable = z.components_schemas_OneOfAllOfIssueWritable();

/**
 * This is a reusable parameter
 */
export const zSimpleParameter = z.components_parameters_SimpleParameter();

export const zCompositionWithOneOfAndProperties = z.components_schemas_CompositionWithOneOfAndProperties();

export const zModelWithOneOfAndProperties = z.components_schemas_ModelWithOneOfAndProperties();

/**
 * Parameter with illegal characters
 */
export const zXFooBar = zModelWithString;

/**
 * A reusable request body
 */
export const zSimpleRequestBody = zModelWithString;

/**
 * A reusable request body
 */
export const zSimpleFormData = zModelWithString;

export const zImportBody = z['paths_/api/v{api-version}/no+tag_post_body']();

export const zImportResponse = z['paths_/api/v{api-version}/no+tag_post_responses']();

/**
 * Success
 */
export const zApiVVersionODataControllerCountResponse = zModelFromZendesk;

export const zGetApiVbyApiVersionSimpleOperationPath = z['paths_/api/v{api-version}/simple:operation_get_path']();

/**
 * Response is a simple number
 */
export const zGetApiVbyApiVersionSimpleOperationResponse = z['paths_/api/v{api-version}/simple:operation_get_responses']();

export const zDeleteFooHeaders = z['paths_/api/v{api-version}/foo/{foo_param}/bar/{BarParam}_delete_headers']();

export const zDeleteFooPath = z['paths_/api/v{api-version}/foo/{foo_param}/bar/{BarParam}_delete_path']();

export const zCallWithDescriptionsQuery = z['paths_/api/v{api-version}/descriptions_post_query']();

export const zDeprecatedCallHeaders = z['paths_/api/v{api-version}/parameters/deprecated_post_headers']();

/**
 * This is the parameter that goes into the body
 */
export const zCallWithParametersBody = z.nullable(z['paths_/api/v{api-version}/parameters/{parameterPath}_post_body']());

export const zCallWithParametersHeaders = z['paths_/api/v{api-version}/parameters/{parameterPath}_post_headers']();

export const zCallWithParametersPath = z['paths_/api/v{api-version}/parameters/{parameterPath}_post_path']();

export const zCallWithParametersQuery = z['paths_/api/v{api-version}/parameters/{parameterPath}_post_query']();

/**
 * This is the parameter that goes into the body
 */
export const zCallWithWeirdParameterNamesBody = z.nullable(z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_body']());

export const zCallWithWeirdParameterNamesHeaders = z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_headers']();

export const zCallWithWeirdParameterNamesPath = z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_path']();

export const zCallWithWeirdParameterNamesQuery = z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_query']();

/**
 * This is a required parameter
 */
export const zGetCallWithOptionalParamBody = zModelWithOneOfEnum;

export const zGetCallWithOptionalParamQuery = z['paths_/api/v{api-version}/parameters_get_query']();

/**
 * This is an optional parameter
 */
export const zPostCallWithOptionalParamBody = z['paths_/api/v{api-version}/parameters_post_body']();

export const zPostCallWithOptionalParamQuery = z['paths_/api/v{api-version}/parameters_post_query']();

export const zPostCallWithOptionalParamResponse = z['paths_/api/v{api-version}/parameters_post_responses']();

/**
 * A reusable request body
 */
export const zPostApiVbyApiVersionRequestBodyBody = zSimpleRequestBody;

export const zPostApiVbyApiVersionRequestBodyQuery = z['paths_/api/v{api-version}/requestBody_post_query']();

/**
 * A reusable request body
 */
export const zPostApiVbyApiVersionFormDataBody = zSimpleFormData;

export const zPostApiVbyApiVersionFormDataQuery = z['paths_/api/v{api-version}/formData_post_query']();

export const zCallWithDefaultParametersQuery = z['paths_/api/v{api-version}/defaults_get_query']();

export const zCallWithDefaultOptionalParametersQuery = z['paths_/api/v{api-version}/defaults_post_query']();

export const zCallToTestOrderOfParamsQuery = z['paths_/api/v{api-version}/defaults_put_query']();

/**
 * Success
 */
export const zCallWithNoContentResponseResponse = z['paths_/api/v{api-version}/no-content_get_responses']();

export const zCallWithResponseAndNoContentResponseResponse = z['paths_/api/v{api-version}/multiple-tags/response-and-no-content_get_responses']();

export const zDummyAResponse = z400;

/**
 * Success
 */
export const zDummyBResponse = z['paths_/api/v{api-version}/multiple-tags/b_get_responses']();

export const zCallWithResponseResponse = zImport;

export const zCallWithDuplicateResponsesResponse = z['paths_/api/v{api-version}/response_post_responses']();

export const zCallWithResponsesResponse = z['paths_/api/v{api-version}/response_put_responses']();

export const zCollectionFormatQuery = z['paths_/api/v{api-version}/collectionFormat_get_query']();

export const zTypesPath = z['paths_/api/v{api-version}/types_get_path']();

export const zTypesQuery = z['paths_/api/v{api-version}/types_get_query']();

export const zTypesResponse = z['paths_/api/v{api-version}/types_get_responses']();

export const zUploadFileBody = z['paths_/api/v{api-version}/upload_post_body']();

export const zUploadFilePath = z['paths_/api/v{api-version}/upload_post_path']();

export const zUploadFileResponse = z['paths_/api/v{api-version}/upload_post_responses']();

export const zFileResponsePath = z['paths_/api/v{api-version}/file/{id}_get_path']();

/**
 * Success
 */
export const zFileResponseResponse = z['paths_/api/v{api-version}/file/{id}_get_responses']();

export const zComplexTypesQuery = z['paths_/api/v{api-version}/complex_get_query']();

/**
 * Successful response
 */
export const zComplexTypesResponse = z['paths_/api/v{api-version}/complex_get_responses']();

/**
 * OK
 */
export const zMultipartResponseResponse = z['paths_/api/v{api-version}/multipart_get_responses']();

export const zMultipartRequestBody = z['paths_/api/v{api-version}/multipart_post_body']();

export const zComplexParamsBody = z['paths_/api/v{api-version}/complex/{id}_put_body']();

export const zComplexParamsPath = z['paths_/api/v{api-version}/complex/{id}_put_path']();

/**
 * Success
 */
export const zComplexParamsResponse = zModelWithString;

export const zTestErrorCodeQuery = z['paths_/api/v{api-version}/error_post_query']();

export const zNonAsciiæøåÆøÅöôêÊ字符串Query = z['paths_/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串_post_query']();

/**
 * Successful response
 */
export const zNonAsciiæøåÆøÅöôêÊ字符串Response = z['paths_/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串_post_responses']();

export const zPutWithFormUrlEncodedBody = zArrayWithStrings;
