// This file is auto-generated by @hey-api/openapi-ts

export { createDocument, type Options } from './sdk.gen';
export type { ClientOptions, CreateDocumentData, CreateDocumentResponse, CreateDocumentResponses, Document } from './types.gen';
