// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteRecordsData, DeleteRecordsResponses, GetRecordsData, GetRecordsErrors, GetStatusData, GetStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

const getStatusResponseTransformer = async (data: unknown) => String(data).length;

const deleteRecordsResponseTransformer = async (data: unknown) => String(data).length;

const getRecordsResponseTransformer = async (data: unknown) => String(data).length;

type GetRecordsTransformedResponses = {
  200: Awaited<ReturnType<typeof getRecordsResponseTransformer>>;
  201: Awaited<ReturnType<typeof getRecordsResponseTransformer>>;
};

export type GetRecordsTransformedResponse = GetRecordsTransformedResponses[keyof GetRecordsTransformedResponses];

export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>): RequestResult<GetStatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({
  responseTransformer: getStatusResponseTransformer,
  url: '/status',
  ...options
});

export const deleteRecords = <ThrowOnError extends boolean = false>(options?: Options<DeleteRecordsData, ThrowOnError>): RequestResult<DeleteRecordsResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<DeleteRecordsResponses, unknown, ThrowOnError>({
  responseTransformer: deleteRecordsResponseTransformer,
  url: '/records',
  ...options
});

export const getRecords = <ThrowOnError extends boolean = false>(options?: Options<GetRecordsData, ThrowOnError>): RequestResult<GetRecordsTransformedResponses, GetRecordsErrors, ThrowOnError> => (options?.client ?? client).get<GetRecordsTransformedResponses, GetRecordsErrors, ThrowOnError>({
  responseTransformer: getRecordsResponseTransformer,
  url: '/records',
  ...options
});
