// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type MockItem = (({
  kind: 1;
} & FooItem) | ({
  kind: 2;
} & BarItem)) & {
  id: string;
  kind: number;
};

export type FooItem = {
  foo: string;
};

export type BarItem = {
  bar: string;
};
