// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Operations2 = {
  getPing: {
    data: GetPingData;
    responses: GetPingResponses;
  };
};

export type Operations = {
  name?: string;
};

export type GetPingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/ping';
};

export type GetPingResponses = {
  /**
   * OK
   */
  200: Operations;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];
