// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type Document = {
  id?: string;
  name?: string;
};

export type PostDocumentsData = {
  body: Document;
  path?: never;
  query?: never;
  url: '/documents';
};

export type PostDocumentsResponses = {
  /**
   * OK
   */
  200: Document;
};

export type PostDocumentsResponse = PostDocumentsResponses[keyof PostDocumentsResponses];
