// This file is auto-generated by @hey-api/openapi-ts

export { type Options, postDocuments } from './sdk.gen';
export type { ClientOptions, Document, PostDocumentsData, PostDocumentsResponse, PostDocumentsResponses } from './types.gen';
