// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';

export const CallWithNoContentResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});
