// This file is auto-generated by @hey-api/openapi-ts

import type * as Effect from 'effect/Effect';
import { HttpClient } from 'effect/unstable/http';
import { HttpApi, HttpApiClient, HttpApiEndpoint, HttpApiGroup, HttpApiSchema } from 'effect/unstable/httpapi';

const NoContentGroup = HttpApiGroup.make('NoContent').add(HttpApiEndpoint.get('callWithNoContentResponse', '/no-content', {
  success: HttpApiSchema.Empty(204)
}));

export const Api = HttpApi.make('Api').add(NoContentGroup);

export function makeClient(options?: {
  readonly baseUrl?: URL | string | undefined;
  readonly transformClient?: ((client: HttpClient.HttpClient) => HttpClient.HttpClient) | undefined;
  readonly transformResponse?: ((effect: Effect.Effect<unknown, unknown, unknown>) => Effect.Effect<unknown, unknown, unknown>) | undefined;
}) {
  return HttpApiClient.make(Api, options);
}
