// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type CallWithNoContentResponseData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/no-content';
};

export type CallWithNoContentResponseResponses = {
  /**
   * No content
   */
  204: unknown;
};
