// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type CreateEventData = {
  body: {
    name: string;
  };
  path?: never;
  query?: never;
  url: '/events';
};

export type CreateEventResponses = {
  /**
   * Created
   */
  201: string;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type SubscribeToEventStreamData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/events/subscribe';
};

export type SubscribeToEventStreamResponses = {
  /**
   * Event stream
   */
  200: {
    [key: string]: unknown;
  };
};

export type SubscribeToEventStreamResponse = SubscribeToEventStreamResponses[keyof SubscribeToEventStreamResponses];

export type ListEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/events/list';
};

export type ListEventsResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];
