// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zExampleRequest = z.object({
  options: z.intersection(z.object({
    optionA: z.boolean().optional(),
    optionB: z.boolean().optional(),
    optionC: z.boolean().optional(),
    optionD: z.boolean().optional()
  }), z.unknown().check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length >= 1, 'Expected at least 1 property')).check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length <= 3, 'Expected at most 3 properties')).transform(() => ({}))),
  recordOptions: z.intersection(z.record(z.string(), z.boolean()), z.unknown().check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length >= 1, 'Expected at least 1 property')).check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length <= 2, 'Expected at most 2 properties')).transform(() => ({}))).optional(),
  strictOptions: z.intersection(z.strictObject({
    optionA: z.boolean().optional(),
    optionB: z.boolean().optional()
  }), z.unknown().check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length >= 1, 'Expected at least 1 property')).check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length <= 2, 'Expected at most 2 properties')).transform(() => ({}))).optional()
});

export const zPropertyCountOne = z.intersection(z.object({
  id: z.string().optional()
}), z.unknown().check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length >= 1, 'Expected at least 1 property')).check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length <= 2, 'Expected at most 2 properties')).transform(() => ({})));

export const zPropertyCountTwo = z.intersection(z.object({
  id: z.string().optional()
}), z.unknown().check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length >= 1, 'Expected at least 1 property')).check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length <= 2, 'Expected at most 2 properties')).transform(() => ({})));

export const zPropertyCountUnion = z.union([
  z.object({
    type: z.literal('one')
  }).and(zPropertyCountOne),
  z.object({
    type: z.literal('two')
  }).and(zPropertyCountTwo)
]);
