# This file is auto-generated by @hey-api/openapi-python

from typing import Literal, Optional, Union

from pydantic import BaseModel, Field, RootModel


class Foo(BaseModel):
    type: str = Field(..., alias="$type")
    foo: Optional[str] = None


class Bar_(BaseModel):
    type: Literal["FooBar"] = Field(..., alias="$type")
    bar: Optional[str] = None


class Bar(Bar_, Foo):
    pass


class Baz_(BaseModel):
    baz: Optional[str] = None
    type: Literal["FooBaz"] = Field(..., alias="$type")


class Baz(Baz_, Foo):
    pass


class Qux_(BaseModel):
    qux: Optional[str] = None
    type: Literal["BarQux"] = Field(..., alias="$type")


class Qux(Qux_, Bar):
    pass


class GetFoosResponse(RootModel[Union[Bar, Baz, Qux]]):
    """OK"""

    root: Union[Bar, Baz, Qux] = Field(..., description="OK")
