# This file is auto-generated by @hey-api/openapi-python

from typing import Any, Literal, Optional, TypeAlias, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Foo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type: str = Field(..., alias="$type")
    foo: Optional[str] = None


class Bar_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type: Literal["FooBar"] = Field(..., alias="$type")
    bar: Optional[str] = None


Bar: TypeAlias = Any


class Baz_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    baz: Optional[str] = None
    type: Literal["FooBaz"] = Field(..., alias="$type")


Baz: TypeAlias = Any


class Qux_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    qux: Optional[str] = None
    type: Literal["BarQux"] = Field(..., alias="$type")


Qux: TypeAlias = Any


class GetFoosResponse(RootModel[Union[Bar, Baz, Qux]]):
    """OK"""

    root: Union[Bar, Baz, Qux] = Field(..., description="OK")
