# This file is auto-generated by @hey-api/openapi-python

from .client import Client


class Sdk(Client):
    def list_things(self):
        return self.client.get("/things")

    def get_thing(self):
        return self.client.get("/things/{id}")

    def create_widget(self):
        return self.client.post("/widgets")
