// This file is auto-generated by @hey-api/openapi-ts

import { HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions as RequestHandlerOptions2 } from 'msw';

import type { ClientOptions, SearchData, SearchResponses } from './types.gen';

export type RequestHandlerOptions = RequestHandlerOptions2 & {
  baseUrl?: ClientOptions['baseUrl'];
  responseFallback?: 'error' | 'passthrough';
};

export type HandleSearchResponse = {
  body: SearchResponses[200];
  status?: 200;
};

/**
 * Handler for the `QUERY /search` operation.
 */
export function handleSearch(response?: HandleSearchResponse | HttpResponseResolver<never, SearchData['body']>, options?: RequestHandlerOptions): HttpHandler {
  return new HttpHandler('QUERY', `${options?.baseUrl ?? '*'}/search`, info => {
    if (typeof response === 'function') {
      return response(info as Parameters<typeof response>[0]);
    }
    const body = response?.body;
    if (body !== undefined) {
      return HttpResponse.json(body, { status: response?.status ?? 200 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type MswHandlerFactories = {
  /**
   * Handler for the `QUERY /search` operation.
   */
  search: typeof handleSearch;
};

export type CreateMswHandlersResult = {
  all: (options?: {
    pick?: {
      [K in keyof MswHandlerFactories]?: Parameters<MswHandlerFactories[K]>[0] | Parameters<MswHandlerFactories[K]>;
    };
  }) => ReadonlyArray<HttpHandler>;
  pick: MswHandlerFactories;
};

export function createMswHandlers(config: RequestHandlerOptions = {}): CreateMswHandlersResult {
  type Handler<R> = (response?: R, options?: RequestHandlerOptions) => HttpHandler;
  function wrap<R>(handler: Handler<R>): Handler<R> {
    return (response, options) => handler(response, { ...config, ...options });
  }
  const pick: CreateMswHandlersResult['pick'] = {
    search: wrap(handleSearch)
  };
  const all: CreateMswHandlersResult['all'] = (options = {}) => {
    type OverrideValue<R> = R | [
      response?: R,
      options?: RequestHandlerOptions
    ];
    function invoke<R>(fn: Handler<R>, override?: OverrideValue<R>): HttpHandler {
      return Array.isArray(override) ? fn(...override) : fn(override);
    }
    const overrides = options.pick ?? {};
    return [invoke(pick.search, overrides.search)];
  };
  return { all, pick };
}
