// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type SearchInput = {
  term: string;
};

export type SearchResult = {
  id: string;
  title: string;
};

export type SearchData = {
  body: SearchInput;
  path?: never;
  query?: {
    limit?: number;
  };
  url: '/search';
};

export type SearchResponses = {
  /**
   * Search results
   */
  200: Array<SearchResult>;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];
