// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/v4';

export const zExampleRequest = z.object({
  options: z.object({
    optionA: z.boolean().optional(),
    optionB: z.boolean().optional()
  }).check(z.refine(value => Object.keys(value).length >= 1))
});
