// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/v4';

export const zFoo = z.strictObject({
  foo: z.string()
});

export const zBar = zFoo.and(z.object({}));

export const zBaz = zFoo.and(z.strictObject({
  bar: z.string()
}));
