# This file is auto-generated by @hey-api/openapi-python

from typing import Any, Literal, TypeAlias, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BlogPostDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type: Literal["BlogPost"] = Field(..., alias="$type")
    id: int
    title: str


class BlogPostWithImageDto_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    image_url: str = Field(..., alias="imageUrl")
    type: Literal["BlogPostWithImage"] = Field(..., alias="$type")


BlogPostWithImageDto: TypeAlias = Any


class GetBlogPostsResponse(RootModel[list[Union[BlogPostDto, BlogPostWithImageDto]]]):
    """List of blog posts"""

    root: list[Union[BlogPostDto, BlogPostWithImageDto]] = Field(..., description="List of blog posts")
