// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, type MutationOptions, type QueryClient, queryOptions } from '@tanstack/solid-query';

import { client } from '../client.gen';
import { addPet, getPet, listPets, type Options } from '../sdk.gen';
import type { AddPetData, AddPetError, AddPetResponse, GetPetData, GetPetError, GetPetResponse, ListPetsData, ListPetsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
  QueryKey<TOptions>[0]
] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listPetsQueryKey = (options?: Options<ListPetsData>) => createQueryKey('listPets', options, false, ['pets']);

export const listPetsOptions = (options?: Options<ListPetsData>) => queryOptions<ListPetsResponse, DefaultError, ListPetsResponse, ReturnType<typeof listPetsQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await listPets({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: listPetsQueryKey(options),
  meta: { operationId: 'listPets' }
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...queryKey[0].body as any,
      ...page.body as any
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    };
  }
  if (page.path) {
    params.path = {
      ...queryKey[0].path as any,
      ...page.path as any
    };
  }
  if (page.query) {
    params.query = {
      ...queryKey[0].query as any,
      ...page.query as any
    };
  }
  return params as unknown as typeof page;
};

export const listPetsInfiniteQueryKey = (options?: Options<ListPetsData>): QueryKey<Options<ListPetsData>> => createQueryKey('listPets', options, true, ['pets']);

export const listPetsInfiniteOptions = (options?: Options<ListPetsData>) => {
  const opts = infiniteQueryOptions<ListPetsResponse, DefaultError, InfiniteData<ListPetsResponse>, QueryKey<Options<ListPetsData>>, number | Pick<QueryKey<Options<ListPetsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
  // @ts-ignore
  {
    queryFn: async ({ pageParam, queryKey, signal }) => {
      // @ts-ignore
      const page: Pick<QueryKey<Options<ListPetsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
        query: {
          page: pageParam
        }
      };
      const params = createInfiniteParams(queryKey, page);
      const { data } = await listPets({
        ...options,
        ...params,
        signal,
        throwOnError: true
      });
      return data;
    },
    queryKey: listPetsInfiniteQueryKey(options),
    meta: { operationId: 'listPets' }
  });
  return opts as Omit<typeof opts, 'initialData'>;
};

export const listPetsGetQueryData = (queryClient: QueryClient, options: Options<ListPetsData> | undefined) => queryClient.getQueryData<ListPetsResponse>(listPetsOptions(options).queryKey);

export const listPetsSetQueryData = (queryClient: QueryClient, options: Options<ListPetsData> | undefined, updater: ListPetsResponse | undefined | ((old: ListPetsResponse | undefined) => ListPetsResponse | undefined)) => queryClient.setQueryData(listPetsOptions(options).queryKey, updater);

export type MutationKey<TOptions extends Partial<Options>> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    tags?: ReadonlyArray<string>;
  }
];

const createMutationKey = <TOptions extends Partial<Options>>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
  MutationKey<TOptions>[0]
] => {
  const params: MutationKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl };
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const addPetMutationKey = (options?: Partial<Options<AddPetData>>) => createMutationKey('addPet', options, ['pets']);

export const addPetMutation = (options?: Partial<Options<AddPetData>>): MutationOptions<AddPetResponse, AddPetError, Options<AddPetData>> => {
  const mutationOptions: MutationOptions<AddPetResponse, AddPetError, Options<AddPetData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await addPet({
        ...options,
        ...fnOptions,
        throwOnError: true
      });
      return data;
    },
    mutationKey: addPetMutationKey(options),
    meta: { operationId: 'addPet' }
  };
  return mutationOptions;
};

export const getPetQueryKey = (options: Options<GetPetData>) => createQueryKey('getPet', options, false, ['pets']);

export const getPetOptions = (options: Options<GetPetData>) => queryOptions<GetPetResponse, GetPetError, GetPetResponse, ReturnType<typeof getPetQueryKey>>({
  queryFn: async ({ queryKey, signal }) => {
    const { data } = await getPet({
      ...options,
      ...queryKey[0],
      signal,
      throwOnError: true
    });
    return data;
  },
  queryKey: getPetQueryKey(options),
  meta: { operationId: 'getPet' }
});

export const getPetGetQueryData = (queryClient: QueryClient, options: Options<GetPetData>) => queryClient.getQueryData<GetPetResponse>(getPetOptions(options).queryKey);

export const getPetSetQueryData = (queryClient: QueryClient, options: Options<GetPetData>, updater: GetPetResponse | undefined | ((old: GetPetResponse | undefined) => GetPetResponse | undefined)) => queryClient.setQueryData(getPetOptions(options).queryKey, updater);
