// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod/v3';

export const zExampleRequest = z.object({
  options: z.object({
    optionA: z.boolean().optional(),
    optionB: z.boolean().optional(),
    optionC: z.boolean().optional(),
    optionD: z.boolean().optional()
  }).refine(value => Object.keys(value).length >= 1).refine(value => Object.keys(value).length <= 3)
});
