# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, Field, RootModel


class Actor(RootModel[str]):
    root: str


class GetWidgetHeaders(BaseModel):
    actor_id: str = Field(..., alias="Actor-Id")


class GetWidgetPath(BaseModel):
    widget_id: str


class ListWidgetsHeaders(BaseModel):
    actor_id: str = Field(..., alias="Actor-Id")


class ListWidgetsQuery(BaseModel):
    status: Optional[str] = None
    tenant: str


class CountWidgetsHeaders(BaseModel):
    actor_id: str = Field(..., alias="Actor-Id")


class ListTenantWidgetsHeaders(BaseModel):
    actor_id: str = Field(..., alias="Actor-Id")


class ListTenantWidgetsPath(BaseModel):
    tenant: str
