# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client


class Sdk(Client):
    def get_widget(self, widget_id: str, actor_id: Optional[str] = None):
        params = build_client_params([{"in": "headers", "key": "actor_id", "map": "Actor-Id"}, {"in": "path", "key": "widget_id"}], widget_id=widget_id, actor_id=actor_id)
        return self.request_options("get", "/widgets/{widget_id}", params)

    def list_widgets(
        self,
        actor_id: Optional[str] = None,
        status: Optional[str] = None,
        tenant: Optional[str] = None,
    ):
        params = build_client_params([{"in": "headers", "key": "actor_id", "map": "Actor-Id"}, {"in": "query", "key": "status"}, {"in": "query", "key": "tenant"}], actor_id=actor_id, status=status, tenant=tenant)
        return self.request_options("get", "/widgets", params)

    def count_widgets(self, actor_id: Optional[str] = None):
        params = build_client_params([{"in": "headers", "key": "actor_id", "map": "Actor-Id"}], actor_id=actor_id)
        return self.request_options("get", "/widgets/actor-only", params)

    def list_tenant_widgets(self, tenant: str, actor_id: Optional[str] = None):
        params = build_client_params([{"in": "headers", "key": "actor_id", "map": "Actor-Id"}, {"in": "path", "key": "tenant"}], tenant=tenant, actor_id=actor_id)
        return self.request_options("get", "/tenants/{tenant}/widgets", params)
