# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, RootModel


class CreateWidget(BaseModel):
    name: str


class GetWidgetPath(BaseModel):
    widget_id: str


class ListWidgetsQuery(BaseModel):
    status: Optional[str] = None


class CreateWidgetBody(RootModel[CreateWidget]):
    root: CreateWidget
