# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, RootModel


class CreateWidget(BaseModel):
    name: str


class WidgetsGetPath(BaseModel):
    widget_id: str


class WidgetsListQuery(BaseModel):
    status: Optional[str] = None


class WidgetsCreateBody(RootModel[CreateWidget]):
    root: CreateWidget


class WidgetsPartsListPath(BaseModel):
    widget_id: str
