# This file is auto-generated by @hey-api/openapi-python

from functools import cached_property

from .client import AsyncClient, Client


class Parts(Client):
    def list(self):
        return self.client.get("/widgets/{widget_id}/parts")


class Widgets(Client):
    def get(self):
        return self.client.get("/widgets/{widget_id}")

    def list(self):
        return self.client.get("/widgets")

    def create(self):
        return self.client.post("/widgets")

    @cached_property
    def parts(self) -> Parts:
        return Parts(client=self.client)


class Sdk(Client):
    @cached_property
    def widgets(self) -> Widgets:
        return Widgets(client=self.client)


class AsyncParts(AsyncClient):
    async def list(self):
        return await self.client.get("/widgets/{widget_id}/parts")


class AsyncWidgets(AsyncClient):
    async def get(self):
        return await self.client.get("/widgets/{widget_id}")

    async def list(self):
        return await self.client.get("/widgets")

    async def create(self):
        return await self.client.post("/widgets")

    @cached_property
    def parts(self) -> AsyncParts:
        return AsyncParts(client=self.client)


class AsyncSdk(AsyncClient):
    @cached_property
    def widgets(self) -> AsyncWidgets:
        return AsyncWidgets(client=self.client)
