# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import AsyncClient, build_client_params, Client
from .pydantic_gen import CreateWidget


class Sdk(Client):
    def get_widget(self, widget_id: str):
        params = build_client_params([{"in": "path", "key": "widget_id"}], widget_id=widget_id)
        return self.request_options("get", "/widgets/{widget_id}", params)

    def list_widgets(self, status: Optional[str] = None):
        params = build_client_params([{"in": "query", "key": "status"}], status=status)
        return self.request_options("get", "/widgets", params)

    def create_widget(self, create_widget: CreateWidget):
        params = build_client_params([{"in": "body", "key": "create_widget", "map": "body"}], create_widget=create_widget)
        return self.request_options("post", "/widgets", params)


class AsyncSdk(AsyncClient):
    async def get_widget(self, widget_id: str):
        params = build_client_params([{"in": "path", "key": "widget_id"}], widget_id=widget_id)
        return await self.request_options("get", "/widgets/{widget_id}", params)

    async def list_widgets(self, status: Optional[str] = None):
        params = build_client_params([{"in": "query", "key": "status"}], status=status)
        return await self.request_options("get", "/widgets", params)

    async def create_widget(self, create_widget: CreateWidget):
        params = build_client_params([{"in": "body", "key": "create_widget", "map": "body"}], create_widget=create_widget)
        return await self.request_options("post", "/widgets", params)
