// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zExampleRequest = z.object({
  options: z.intersection(z.object({
    optionA: z.boolean().optional(),
    optionB: z.boolean().optional(),
    optionC: z.boolean().optional(),
    optionD: z.boolean().optional()
  }), z.unknown().refine(value => typeof value === 'object' && value !== null && Object.keys(value).length >= 1, 'Expected at least 1 property').refine(value => typeof value === 'object' && value !== null && Object.keys(value).length <= 3, 'Expected at most 3 properties').transform(() => ({})))
});
