// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:3000/base' | (string & {});
};

export type ExternalRefA = ExternalSharedModel;

export type ExternalRefB = ExternalSharedModel;

/**
 * Testing multiline comments in string: First line
 * Second line
 *
 * Fourth line
 */
export type CommentWithBreaks = (typeof globalThis).components_schemas_CommentWithBreaks;

/**
 * Testing backticks in string: `backticks` and ```multiple backticks``` should work
 */
export type CommentWithBackticks = (typeof globalThis).components_schemas_CommentWithBackticks;

/**
 * Testing backticks and quotes in string: `backticks`, 'quotes', "double quotes" and ```multiple backticks``` should work
 */
export type CommentWithBackticksAndQuotes = (typeof globalThis).components_schemas_CommentWithBackticksAndQuotes;

/**
 * Testing slashes in string: \backwards\\\ and /forwards/// should work
 */
export type CommentWithSlashes = (typeof globalThis).components_schemas_CommentWithSlashes;

/**
 * Testing expression placeholders in string: ${expression} should work
 */
export type CommentWithExpressionPlaceholders = (typeof globalThis).components_schemas_CommentWithExpressionPlaceholders;

/**
 * Testing quotes in string: 'single quote''' and "double quotes""" should work
 */
export type CommentWithQuotes = (typeof globalThis).components_schemas_CommentWithQuotes;

/**
 * Testing reserved characters in string: * inline * and ** inline ** should work
 */
export type CommentWithReservedCharacters = (typeof globalThis).components_schemas_CommentWithReservedCharacters;

/**
 * This is a simple number
 */
export type SimpleInteger = (typeof globalThis).components_schemas_SimpleInteger;

/**
 * This is a simple boolean
 */
export type SimpleBoolean = (typeof globalThis).components_schemas_SimpleBoolean;

/**
 * This is a simple string
 */
export type SimpleString = (typeof globalThis).components_schemas_SimpleString;

/**
 * A string with non-ascii (unicode) characters valid in typescript identifiers (æøåÆØÅöÔèÈ字符串)
 */
export type NonAsciiStringæøåÆøÅöôêÊ字符串 = (typeof globalThis).components_schemas_NonAsciiStringæøåÆØÅöôêÊ字符串;

/**
 * This is a simple file
 */
export type SimpleFile = (typeof globalThis).components_schemas_SimpleFile;

export type SimpleReference = ModelWithString;

/**
 * This is a simple string
 */
export type SimpleStringWithPattern = (typeof globalThis).components_schemas_SimpleStringWithPattern;

/**
 * This is a simple enum with strings
 */
export type EnumWithStrings = (typeof globalThis).components_schemas_EnumWithStrings;

/**
 * This is a simple enum with numbers
 */
export type EnumWithNumbers = (typeof globalThis).components_schemas_EnumWithNumbers;

/**
 * Success=1,Warning=2,Error=3
 */
export type EnumFromDescription = (typeof globalThis).components_schemas_EnumFromDescription;

/**
 * This is a simple enum with numbers
 */
export type EnumWithExtensions = (typeof globalThis).components_schemas_EnumWithExtensions;

/**
 * This is a simple array with numbers
 */
export type ArrayWithNumbers = Array<(typeof globalThis).components_schemas_ArrayWithNumbers_items_0>;

/**
 * This is a simple array with booleans
 */
export type ArrayWithBooleans = Array<(typeof globalThis).components_schemas_ArrayWithBooleans_items_0>;

/**
 * This is a simple array with strings
 */
export type ArrayWithStrings = Array<(typeof globalThis).components_schemas_ArrayWithStrings_items_0>;

/**
 * This is a simple array with references
 */
export type ArrayWithReferences = Array<ModelWithString>;

/**
 * This is a simple array containing an array
 */
export type ArrayWithArray = Array<Array<ModelWithString>>;

/**
 * This is a simple array with properties
 */
export type ArrayWithProperties = Array<(typeof globalThis).components_schemas_ArrayWithProperties_items_0>;

/**
 * This is a string dictionary
 */
export type DictionaryWithString = (typeof globalThis).components_schemas_DictionaryWithString;

/**
 * This is a string reference
 */
export type DictionaryWithReference = (typeof globalThis).components_schemas_DictionaryWithReference;

/**
 * This is a complex dictionary
 */
export type DictionaryWithArray = (typeof globalThis).components_schemas_DictionaryWithArray;

/**
 * This is a string dictionary
 */
export type DictionaryWithDictionary = (typeof globalThis).components_schemas_DictionaryWithDictionary;

/**
 * This is a complex dictionary
 */
export type DictionaryWithProperties = (typeof globalThis).components_schemas_DictionaryWithProperties;

/**
 * This is a type-only model that defines Date as a string
 */
export type Date = (typeof globalThis).components_schemas_Date;

/**
 * This is a model with one number property
 */
export type ModelWithInteger = (typeof globalThis).components_schemas_ModelWithInteger;

/**
 * This is a model with one boolean property
 */
export type ModelWithBoolean = (typeof globalThis).components_schemas_ModelWithBoolean;

/**
 * This is a model with one string property
 */
export type ModelWithString = (typeof globalThis).components_schemas_ModelWithString;

/**
 * This is a model with one string property
 */
export type ModelWithStringError = (typeof globalThis).components_schemas_ModelWithStringError;

/**
 * This is a model with one string property
 */
export type ModelWithNullableString = (typeof globalThis).components_schemas_ModelWithNullableString;

/**
 * This is a model with one enum
 */
export type ModelWithEnum = (typeof globalThis).components_schemas_ModelWithEnum;

/**
 * This is a model with one enum
 */
export type ModelWithEnumFromDescription = (typeof globalThis).components_schemas_ModelWithEnumFromDescription;

/**
 * This is a model with nested enums
 */
export type ModelWithNestedEnums = (typeof globalThis).components_schemas_ModelWithNestedEnums;

/**
 * This is a model with one property containing a reference
 */
export type ModelWithReference = (typeof globalThis).components_schemas_ModelWithReference;

/**
 * This is a model with one property containing an array
 */
export type ModelWithArray = (typeof globalThis).components_schemas_ModelWithArray;

/**
 * This is a model with one property containing a dictionary
 */
export type ModelWithDictionary = (typeof globalThis).components_schemas_ModelWithDictionary;

/**
 * This is a model with one property containing a circular reference
 */
export type ModelWithCircularReference = (typeof globalThis).components_schemas_ModelWithCircularReference;

/**
 * This is a model with one nested property
 */
export type ModelWithProperties = (typeof globalThis).components_schemas_ModelWithProperties;

/**
 * This is a model with one nested property
 */
export type ModelWithNestedProperties = (typeof globalThis).components_schemas_ModelWithNestedProperties;

/**
 * This is a model with duplicated properties
 */
export type ModelWithDuplicateProperties = (typeof globalThis).components_schemas_ModelWithDuplicateProperties;

/**
 * This is a model with ordered properties
 */
export type ModelWithOrderedProperties = (typeof globalThis).components_schemas_ModelWithOrderedProperties;

/**
 * This is a model with duplicated imports
 */
export type ModelWithDuplicateImports = (typeof globalThis).components_schemas_ModelWithDuplicateImports;

/**
 * This is a model that extends another model
 */
export type ModelThatExtends = (typeof globalThis).components_schemas_ModelThatExtends;

/**
 * This is a model that extends another model
 */
export type ModelThatExtendsExtends = (typeof globalThis).components_schemas_ModelThatExtendsExtends;

export type Default = (typeof globalThis).components_schemas_default;

/**
 * This is a model that contains a some patterns
 */
export type ModelWithPattern = (typeof globalThis).components_schemas_ModelWithPattern;

export type ParameterActivityParams = (typeof globalThis)['components_schemas_parameter.ActivityParams'];

export type ResponsePostActivityResponse = (typeof globalThis)['components_schemas_response.PostActivityResponse'];

export type FailureFailure = (typeof globalThis)['components_schemas_failure.Failure'];

export type ExternalSharedModel = (typeof globalThis).components_schemas_ExternalSharedModel;

/**
 * This is a model with one property containing a reference
 */
export type ModelWithReferenceWritable = (typeof globalThis).components_schemas_ModelWithReferenceWritable;

/**
 * This is a model with one nested property
 */
export type ModelWithPropertiesWritable = (typeof globalThis).components_schemas_ModelWithPropertiesWritable;

/**
 * This is a model that contains a some patterns
 */
export type ModelWithPatternWritable = (typeof globalThis).components_schemas_ModelWithPatternWritable;

export type ServiceWithEmptyTagData = (typeof globalThis)['paths_/api/v{api-version}/no+tag_get_serviceWithEmptyTag_data'];

export type PatchApiVbyApiVersionNoTagData = (typeof globalThis)['paths_/api/v{api-version}/no+tag_patch_patchApiVbyApiVersionNoTag_data'];

export type PatchApiVbyApiVersionNoTagResponses = (typeof globalThis)['paths_/api/v{api-version}/no+tag_patch_patchApiVbyApiVersionNoTag_responses'];

export type FooWowData = (typeof globalThis)['paths_/api/v{api-version}/no+tag_put_fooWow_data'];

export type FooWowResponses = (typeof globalThis)['paths_/api/v{api-version}/no+tag_put_fooWow_responses'];

export type DeleteCallWithoutParametersAndResponseData = (typeof globalThis)['paths_/api/v{api-version}/simple_delete_deleteCallWithoutParametersAndResponse_data'];

export type GetCallWithoutParametersAndResponseData = (typeof globalThis)['paths_/api/v{api-version}/simple_get_getCallWithoutParametersAndResponse_data'];

export type HeadCallWithoutParametersAndResponseData = (typeof globalThis)['paths_/api/v{api-version}/simple_head_headCallWithoutParametersAndResponse_data'];

export type OptionsCallWithoutParametersAndResponseData = (typeof globalThis)['paths_/api/v{api-version}/simple_options_optionsCallWithoutParametersAndResponse_data'];

export type PatchCallWithoutParametersAndResponseData = (typeof globalThis)['paths_/api/v{api-version}/simple_patch_patchCallWithoutParametersAndResponse_data'];

export type PostCallWithoutParametersAndResponseData = (typeof globalThis)['paths_/api/v{api-version}/simple_post_postCallWithoutParametersAndResponse_data'];

export type PutCallWithoutParametersAndResponseData = (typeof globalThis)['paths_/api/v{api-version}/simple_put_putCallWithoutParametersAndResponse_data'];

export type CallWithDescriptionsData = (typeof globalThis)['paths_/api/v{api-version}/descriptions/_post_callWithDescriptions_data'];

export type CallWithParametersData = (typeof globalThis)['paths_/api/v{api-version}/parameters/{parameterPath}_post_callWithParameters_data'];

export type CallWithWeirdParameterNamesData = (typeof globalThis)['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_callWithWeirdParameterNames_data'];

export type CallWithDefaultParametersData = (typeof globalThis)['paths_/api/v{api-version}/defaults_get_callWithDefaultParameters_data'];

export type CallWithDefaultOptionalParametersData = (typeof globalThis)['paths_/api/v{api-version}/defaults_post_callWithDefaultOptionalParameters_data'];

export type CallToTestOrderOfParamsData = (typeof globalThis)['paths_/api/v{api-version}/defaults_put_callToTestOrderOfParams_data'];

export type DuplicateNameData = (typeof globalThis)['paths_/api/v{api-version}/duplicate_delete_duplicateName_data'];

export type DuplicateName2Data = (typeof globalThis)['paths_/api/v{api-version}/duplicate_get_duplicateName2_data'];

export type DuplicateName3Data = (typeof globalThis)['paths_/api/v{api-version}/duplicate_post_duplicateName3_data'];

export type DuplicateName4Data = (typeof globalThis)['paths_/api/v{api-version}/duplicate_put_duplicateName4_data'];

export type CallWithNoContentResponseData = (typeof globalThis)['paths_/api/v{api-version}/no-content_get_callWithNoContentResponse_data'];

export type CallWithNoContentResponseResponses = (typeof globalThis)['paths_/api/v{api-version}/no-content_get_callWithNoContentResponse_responses'];

export type CallWithResponseAndNoContentResponseData = (typeof globalThis)['paths_/api/v{api-version}/multiple-tags/response-and-no-content_get_callWithResponseAndNoContentResponse_data'];

export type CallWithResponseAndNoContentResponseResponses = (typeof globalThis)['paths_/api/v{api-version}/multiple-tags/response-and-no-content_get_callWithResponseAndNoContentResponse_responses'];

export type CallWithResponseAndNoContentResponseResponse = CallWithResponseAndNoContentResponseResponses[keyof CallWithResponseAndNoContentResponseResponses];

export type DummyAData = (typeof globalThis)['paths_/api/v{api-version}/multiple-tags/a_get_dummyA_data'];

export type DummyAResponses = (typeof globalThis)['paths_/api/v{api-version}/multiple-tags/a_get_dummyA_responses'];

export type DummyBData = (typeof globalThis)['paths_/api/v{api-version}/multiple-tags/b_get_dummyB_data'];

export type DummyBResponses = (typeof globalThis)['paths_/api/v{api-version}/multiple-tags/b_get_dummyB_responses'];

export type CallWithResponseData = (typeof globalThis)['paths_/api/v{api-version}/response_get_callWithResponse_data'];

export type CallWithResponseResponses = (typeof globalThis)['paths_/api/v{api-version}/response_get_callWithResponse_responses'];

export type CallWithResponseResponse = CallWithResponseResponses[keyof CallWithResponseResponses];

export type CallWithDuplicateResponsesData = (typeof globalThis)['paths_/api/v{api-version}/response_post_callWithDuplicateResponses_data'];

export type CallWithDuplicateResponsesErrors = (typeof globalThis)['paths_/api/v{api-version}/response_post_callWithDuplicateResponses_errors'];

export type CallWithDuplicateResponsesError = CallWithDuplicateResponsesErrors[keyof CallWithDuplicateResponsesErrors];

export type CallWithDuplicateResponsesResponses = (typeof globalThis)['paths_/api/v{api-version}/response_post_callWithDuplicateResponses_responses'];

export type CallWithDuplicateResponsesResponse = CallWithDuplicateResponsesResponses[keyof CallWithDuplicateResponsesResponses];

export type CallWithResponsesData = (typeof globalThis)['paths_/api/v{api-version}/response_put_callWithResponses_data'];

export type CallWithResponsesErrors = (typeof globalThis)['paths_/api/v{api-version}/response_put_callWithResponses_errors'];

export type CallWithResponsesError = CallWithResponsesErrors[keyof CallWithResponsesErrors];

export type CallWithResponsesResponses = (typeof globalThis)['paths_/api/v{api-version}/response_put_callWithResponses_responses'];

export type CallWithResponsesResponse = CallWithResponsesResponses[keyof CallWithResponsesResponses];

export type CollectionFormatData = (typeof globalThis)['paths_/api/v{api-version}/collectionFormat_get_collectionFormat_data'];

export type TypesData = (typeof globalThis)['paths_/api/v{api-version}/types_get_types_data'];

export type TypesResponses = (typeof globalThis)['paths_/api/v{api-version}/types_get_types_responses'];

export type TypesResponse = TypesResponses[keyof TypesResponses];

export type ComplexTypesData = (typeof globalThis)['paths_/api/v{api-version}/complex_get_complexTypes_data'];

export type ComplexTypesErrors = (typeof globalThis)['paths_/api/v{api-version}/complex_get_complexTypes_errors'];

export type ComplexTypesResponses = (typeof globalThis)['paths_/api/v{api-version}/complex_get_complexTypes_responses'];

export type ComplexTypesResponse = ComplexTypesResponses[keyof ComplexTypesResponses];

export type CallWithResultFromHeaderData = (typeof globalThis)['paths_/api/v{api-version}/header_post_callWithResultFromHeader_data'];

export type CallWithResultFromHeaderErrors = (typeof globalThis)['paths_/api/v{api-version}/header_post_callWithResultFromHeader_errors'];

export type CallWithResultFromHeaderResponses = (typeof globalThis)['paths_/api/v{api-version}/header_post_callWithResultFromHeader_responses'];

export type TestErrorCodeData = (typeof globalThis)['paths_/api/v{api-version}/error_post_testErrorCode_data'];

export type TestErrorCodeErrors = (typeof globalThis)['paths_/api/v{api-version}/error_post_testErrorCode_errors'];

export type TestErrorCodeResponses = (typeof globalThis)['paths_/api/v{api-version}/error_post_testErrorCode_responses'];

export type NonAsciiæøåÆøÅöôêÊ字符串Data = (typeof globalThis)['paths_/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串_post_nonAsciiæøåÆøÅöôêÊ字符串_data'];

export type NonAsciiæøåÆøÅöôêÊ字符串Responses = (typeof globalThis)['paths_/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串_post_nonAsciiæøåÆøÅöôêÊ字符串_responses'];

export type NonAsciiæøåÆøÅöôêÊ字符串Response = NonAsciiæøåÆøÅöôêÊ字符串Responses[keyof NonAsciiæøåÆøÅöôêÊ字符串Responses];

export type PostApiVbyApiVersionBodyData = (typeof globalThis)['paths_/api/v{api-version}/body_post_postApiVbyApiVersionBody_data'];

export type PostApiVbyApiVersionBodyErrors = (typeof globalThis)['paths_/api/v{api-version}/body_post_postApiVbyApiVersionBody_errors'];

export type PostApiVbyApiVersionBodyError = PostApiVbyApiVersionBodyErrors[keyof PostApiVbyApiVersionBodyErrors];

export type PostApiVbyApiVersionBodyResponses = (typeof globalThis)['paths_/api/v{api-version}/body_post_postApiVbyApiVersionBody_responses'];

export type PostApiVbyApiVersionBodyResponse = PostApiVbyApiVersionBodyResponses[keyof PostApiVbyApiVersionBodyResponses];
