// This file is auto-generated by @hey-api/openapi-ts

import useSWR from 'swr';

import { getFoo, getFooBar } from './sdk.gen';

export const useGetFoo = () => useSWR('/foo', async () => await getFoo({ throwOnError: true }));

export const useGetFooBar = () => useSWR('/foo/bar', async () => await getFooBar({ throwOnError: true }));
