// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zExampleRequest = z.object({
  options: z.object({
    optionA: z.optional(z.boolean()),
    optionB: z.optional(z.boolean())
  }).check(z.refine(value => Object.keys(value).length >= 1)).check(z.refine(value => Object.keys(value).length <= 1))
});
