// This file is auto-generated by @hey-api/openapi-ts

export { addPet, getPet, listPets, type Options } from './sdk.gen';
export type { AddPetData, AddPetError, AddPetErrors, AddPetResponse, AddPetResponses, ApiError, ClientOptions, GetPetData, GetPetError, GetPetErrors, GetPetResponse, GetPetResponses, ListPetsData, ListPetsResponse, ListPetsResponses, Pet } from './types.gen';
