// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddPetData, AddPetErrors, AddPetResponses, GetPetData, GetPetErrors, GetPetResponses, ListPetsData, ListPetsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const listPets = <ThrowOnError extends boolean = false>(options?: Options<ListPetsData, ThrowOnError>): RequestResult<ListPetsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListPetsResponses, unknown, ThrowOnError>({ url: '/pets', ...options });

export const addPet = <ThrowOnError extends boolean = false>(options: Options<AddPetData, ThrowOnError>): RequestResult<AddPetResponses, AddPetErrors, ThrowOnError> => (options.client ?? client).post<AddPetResponses, AddPetErrors, ThrowOnError>({
  url: '/pets',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers
  }
});

export const getPet = <ThrowOnError extends boolean = false>(options: Options<GetPetData, ThrowOnError>): RequestResult<GetPetResponses, GetPetErrors, ThrowOnError> => (options.client ?? client).get<GetPetResponses, GetPetErrors, ThrowOnError>({ url: '/pets/{petId}', ...options });
