// This file is auto-generated by @hey-api/openapi-ts

import useSWR from 'swr';

import { getFoo, getFooBar } from './sdk.gen';

export const useGetFoo = () => useSWR('/foo', async () => {
  const { data } = await getFoo({ throwOnError: true });
  return data;
});

export const useGetFooBar = () => useSWR('/foo/bar', async () => {
  const { data } = await getFooBar({ throwOnError: true });
  return data;
});
