# This file is auto-generated by @hey-api/openapi-python

from pydantic import BaseModel, Field


class GadgetsWidgetsListPath(BaseModel):
    gadget_id: str = Field(..., alias="gadgetId", description="Gadget ID")
