# This file is auto-generated by @hey-api/openapi-python

from functools import cached_property

from .client import Client


class Widgets_(Client):
    def list(self):
        """List Gadget Widgets"""

        return self.client.get("/gadgets/{gadgetId}/widgets")


class Gadgets(Client):
    @cached_property
    def widgets(self) -> Widgets_:
        return Widgets_(client=self.client)


class Widgets(Client):
    def list(self):
        """List Widgets"""

        return self.client.get("/widgets")

    def create(self):
        """Create Widget"""

        return self.client.post("/widgets")


class Sdk(Client):
    @cached_property
    def gadgets(self) -> Gadgets:
        return Gadgets(client=self.client)

    @cached_property
    def widgets(self) -> Widgets:
        return Widgets(client=self.client)
