// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { fooBarPost, fooBarPut, fooPost, fooPut, getFoo, getFooBar, type Options } from '../sdk.gen';
import type { FooBarPostData, FooBarPostResponse, FooBarPutData, FooBarPutResponse, FooPostData, FooPostResponse, FooPutData, FooPutResponse, GetFooBarData, GetFooBarResponse, GetFooData, GetFooResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'path'> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
  QueryKey<TOptions>[0]
] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const getFooQueryKey = (options?: Options<GetFooData>) => createQueryKey('getFoo', options);

export const getFooQuery = defineQueryOptions<Options<GetFooData>, GetFooResponse, Error>((options?: Options<GetFooData>) => ({
  key: getFooQueryKey(options),
  query: async (context) => await getFoo({
    ...options,
    ...context,
    throwOnError: true
  })
}));

export const fooPostMutation = (options?: Partial<Options<FooPostData>>): UseMutationOptions<FooPostResponse, Options<FooPostData>, Error> => ({
  mutation: async (vars) => await fooPost({
    ...options,
    ...vars,
    throwOnError: true
  })
});

export const fooPutMutation = (options?: Partial<Options<FooPutData>>): UseMutationOptions<FooPutResponse, Options<FooPutData>, Error> => ({
  mutation: async (vars) => await fooPut({
    ...options,
    ...vars,
    throwOnError: true
  })
});

export const getFooBarQueryKey = (options?: Options<GetFooBarData>) => createQueryKey('getFooBar', options);

export const getFooBarQuery = defineQueryOptions<Options<GetFooBarData>, GetFooBarResponse, Error>((options?: Options<GetFooBarData>) => ({
  key: getFooBarQueryKey(options),
  query: async (context) => await getFooBar({
    ...options,
    ...context,
    throwOnError: true
  })
}));

export const fooBarPostMutation = (options?: Partial<Options<FooBarPostData>>): UseMutationOptions<FooBarPostResponse, Options<FooBarPostData>, Error> => ({
  mutation: async (vars) => await fooBarPost({
    ...options,
    ...vars,
    throwOnError: true
  })
});

export const fooBarPutMutation = (options?: Partial<Options<FooBarPutData>>): UseMutationOptions<FooBarPutResponse, Options<FooBarPutData>, Error> => ({
  mutation: async (vars) => await fooBarPut({
    ...options,
    ...vars,
    throwOnError: true
  })
});
