// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';

export const ModelWithStringSchema = Schema.Struct({
  prop: Schema.optionalKey(Schema.String)
});

export const DeleteFooDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.Struct({
    'api-version': Schema.String,
    foo_param: Schema.String,
    BarParam: Schema.String
  }),
  query: Schema.optionalKey(Schema.Never),
  headers: Schema.Struct({
    'x-Foo-Bar': ModelWithStringSchema
  })
});

/**
 * No content
 */
export const DeleteFooResponseSchema = Schema.Void.annotate({ description: 'No content' });
