// This file is auto-generated by @hey-api/openapi-ts

export { deleteFoo, type Options } from './sdk.gen';
export type { ClientOptions, DeleteFooData, DeleteFooResponse, DeleteFooResponses, ModelWithString } from './types.gen';
