// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import { DeleteFooDataSchema, DeleteFooResponseSchema } from './effect-schema.gen';
import type { DeleteFooData, DeleteFooResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, TResponse = unknown> = Options2<TData, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const deleteFoo = (options: Options<DeleteFooData>): RequestResult<DeleteFooResponses, unknown> => (options.client ?? client).delete<DeleteFooResponses, unknown>({
  requestValidator: async (data) => Schema.decodeUnknownPromise(DeleteFooDataSchema)(data),
  responseTransformer: async (data) => Schema.decodeUnknownPromise(DeleteFooResponseSchema)(data),
  url: '/api/v{api-version}/foo/{foo_param}/bar/{BarParam}',
  ...options
});
