// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ModelWithString = {
  prop?: string;
};

export type DeleteFooData = {
  body?: never;
  headers: {
    'x-Foo-Bar': ModelWithString;
  };
  path: {
    'api-version': string;
    foo_param: string;
    BarParam: string;
  };
  query?: never;
  url: '/api/v{api-version}/foo/{foo_param}/bar/{BarParam}';
};

export type DeleteFooResponses = {
  /**
   * No content
   */
  204: void;
};

export type DeleteFooResponse = DeleteFooResponses[keyof DeleteFooResponses];
