// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod/v3';

/**
 * Testing multiline comments in string: First line
 * Second line
 *
 * Fourth line
 */
export const zCommentWithBreaks = z.components_schemas_CommentWithBreaks();

/**
 * Testing backticks in string: `backticks` and ```multiple backticks``` should work
 */
export const zCommentWithBackticks = z.components_schemas_CommentWithBackticks();

/**
 * Testing backticks and quotes in string: `backticks`, 'quotes', "double quotes" and ```multiple backticks``` should work
 */
export const zCommentWithBackticksAndQuotes = z.components_schemas_CommentWithBackticksAndQuotes();

/**
 * Testing slashes in string: \backwards\\\ and /forwards/// should work
 */
export const zCommentWithSlashes = z.components_schemas_CommentWithSlashes();

/**
 * Testing expression placeholders in string: ${expression} should work
 */
export const zCommentWithExpressionPlaceholders = z.components_schemas_CommentWithExpressionPlaceholders();

/**
 * Testing quotes in string: 'single quote''' and "double quotes""" should work
 */
export const zCommentWithQuotes = z.components_schemas_CommentWithQuotes();

/**
 * Testing reserved characters in string: * inline * and ** inline ** should work
 */
export const zCommentWithReservedCharacters = z.components_schemas_CommentWithReservedCharacters();

/**
 * This is a simple number
 */
export const zSimpleInteger = z.components_schemas_SimpleInteger();

/**
 * This is a simple boolean
 */
export const zSimpleBoolean = z.components_schemas_SimpleBoolean();

/**
 * This is a simple string
 */
export const zSimpleString = z.components_schemas_SimpleString();

/**
 * A string with non-ascii (unicode) characters valid in typescript identifiers (æøåÆØÅöÔèÈ字符串)
 */
export const zNonAsciiStringæøåÆøÅöôêÊ字符串 = z.components_schemas_NonAsciiStringæøåÆØÅöôêÊ字符串();

/**
 * This is a simple file
 */
export const zSimpleFile = z.components_schemas_SimpleFile();

/**
 * This is a simple string
 */
export const zSimpleStringWithPattern = z.components_schemas_SimpleStringWithPattern();

/**
 * This is a simple enum with strings
 */
export const zEnumWithStrings = z.components_schemas_EnumWithStrings();

/**
 * This is a simple enum with numbers
 */
export const zEnumWithNumbers = z.components_schemas_EnumWithNumbers();

/**
 * Success=1,Warning=2,Error=3
 */
export const zEnumFromDescription = z.components_schemas_EnumFromDescription();

/**
 * This is a simple enum with numbers
 */
export const zEnumWithExtensions = z.components_schemas_EnumWithExtensions();

/**
 * This is a simple array with numbers
 */
export const zArrayWithNumbers = z.components_schemas_ArrayWithNumbers();

/**
 * This is a simple array with booleans
 */
export const zArrayWithBooleans = z.components_schemas_ArrayWithBooleans();

/**
 * This is a simple array with strings
 */
export const zArrayWithStrings = z.components_schemas_ArrayWithStrings();

/**
 * This is a simple array with properties
 */
export const zArrayWithProperties = z.components_schemas_ArrayWithProperties();

/**
 * This is a string dictionary
 */
export const zDictionaryWithString = z.components_schemas_DictionaryWithString();

/**
 * This is a string dictionary
 */
export const zDictionaryWithDictionary = z.components_schemas_DictionaryWithDictionary();

/**
 * This is a complex dictionary
 */
export const zDictionaryWithProperties = z.components_schemas_DictionaryWithProperties();

/**
 * This is a type-only model that defines Date as a string
 */
export const zDate = z.components_schemas_Date();

/**
 * This is a model with one number property
 */
export const zModelWithInteger = z.components_schemas_ModelWithInteger();

/**
 * This is a model with one boolean property
 */
export const zModelWithBoolean = z.components_schemas_ModelWithBoolean();

/**
 * This is a model with one string property
 */
export const zModelWithString = z.components_schemas_ModelWithString();

export const zSimpleReference = zModelWithString;

/**
 * This is a simple array with references
 */
export const zArrayWithReferences = z.components_schemas_ArrayWithReferences();

/**
 * This is a simple array containing an array
 */
export const zArrayWithArray = z.components_schemas_ArrayWithArray();

/**
 * This is a string reference
 */
export const zDictionaryWithReference = z.components_schemas_DictionaryWithReference();

/**
 * This is a complex dictionary
 */
export const zDictionaryWithArray = z.components_schemas_DictionaryWithArray();

/**
 * This is a model with one string property
 */
export const zModelWithStringError = z.components_schemas_ModelWithStringError();

/**
 * This is a model with one string property
 */
export const zModelWithNullableString = z.components_schemas_ModelWithNullableString();

/**
 * This is a model with one enum
 */
export const zModelWithEnum = z.components_schemas_ModelWithEnum();

/**
 * This is a model with one enum
 */
export const zModelWithEnumFromDescription = z.components_schemas_ModelWithEnumFromDescription();

/**
 * This is a model with nested enums
 */
export const zModelWithNestedEnums = z.components_schemas_ModelWithNestedEnums();

/**
 * This is a model with one property containing an array
 */
export const zModelWithArray = z.components_schemas_ModelWithArray();

/**
 * This is a model with one property containing a dictionary
 */
export const zModelWithDictionary = z.components_schemas_ModelWithDictionary();

/**
 * This is a model with one property containing a circular reference
 */
export const zModelWithCircularReference = z.components_schemas_ModelWithCircularReference();

/**
 * This is a model with one nested property
 */
export const zModelWithProperties = z.components_schemas_ModelWithProperties();

/**
 * This is a model with one property containing a reference
 */
export const zModelWithReference = z.components_schemas_ModelWithReference();

/**
 * This is a model with one nested property
 */
export const zModelWithNestedProperties = z.components_schemas_ModelWithNestedProperties();

/**
 * This is a model with duplicated properties
 */
export const zModelWithDuplicateProperties = z.components_schemas_ModelWithDuplicateProperties();

/**
 * This is a model with ordered properties
 */
export const zModelWithOrderedProperties = z.components_schemas_ModelWithOrderedProperties();

/**
 * This is a model with duplicated imports
 */
export const zModelWithDuplicateImports = z.components_schemas_ModelWithDuplicateImports();

/**
 * This is a model that extends another model
 */
export const zModelThatExtends = z.components_schemas_ModelThatExtends();

/**
 * This is a model that extends another model
 */
export const zModelThatExtendsExtends = z.components_schemas_ModelThatExtendsExtends();

export const zDefault = z.components_schemas_default();

/**
 * This is a model that contains a some patterns
 */
export const zModelWithPattern = z.components_schemas_ModelWithPattern();

export const zParameterActivityParams = z['components_schemas_parameter.ActivityParams']();

export const zResponsePostActivityResponse = z['components_schemas_response.PostActivityResponse']();

export const zFailureFailure = z['components_schemas_failure.Failure']();

export const zExternalSharedModel = z.components_schemas_ExternalSharedModel();

export const zExternalRefA = zExternalSharedModel;

export const zExternalRefB = zExternalSharedModel;

/**
 * This is a model with one nested property
 */
export const zModelWithPropertiesWritable = z.components_schemas_ModelWithPropertiesWritable();

/**
 * This is a model with one property containing a reference
 */
export const zModelWithReferenceWritable = z.components_schemas_ModelWithReferenceWritable();

/**
 * This is a model that contains a some patterns
 */
export const zModelWithPatternWritable = z.components_schemas_ModelWithPatternWritable();

export const zCallWithDescriptionsQuery = z['paths_/api/v{api-version}/descriptions/_post_query']();

export const zCallWithParametersHeaders = z['paths_/api/v{api-version}/parameters/{parameterPath}_post_headers']();

export const zCallWithParametersPath = z['paths_/api/v{api-version}/parameters/{parameterPath}_post_path']();

export const zCallWithParametersQuery = z['paths_/api/v{api-version}/parameters/{parameterPath}_post_query']();

/**
 * This is the parameter that is sent as request body
 */
export const zCallWithWeirdParameterNamesBody = z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_body']();

export const zCallWithWeirdParameterNamesHeaders = z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_headers']();

export const zCallWithWeirdParameterNamesPath = z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_path']();

export const zCallWithWeirdParameterNamesQuery = z['paths_/api/v{api-version}/parameters/{parameter.path.1}/{parameter-path-2}/{PARAMETER-PATH-3}_post_query']();

export const zCallWithDefaultParametersQuery = z['paths_/api/v{api-version}/defaults_get_query']();

export const zCallWithDefaultOptionalParametersQuery = z['paths_/api/v{api-version}/defaults_post_query']();

export const zCallToTestOrderOfParamsQuery = z['paths_/api/v{api-version}/defaults_put_query']();

export const zCallWithResponseAndNoContentResponseResponse = z['paths_/api/v{api-version}/multiple-tags/response-and-no-content_get_responses']();

/**
 * Message for default response
 */
export const zCallWithResponseResponse = zModelWithString;

/**
 * Message for 201 response
 */
export const zCallWithDuplicateResponsesResponse = zModelWithString;

export const zCallWithResponsesResponse = z['paths_/api/v{api-version}/response_put_responses']();

export const zCollectionFormatQuery = z['paths_/api/v{api-version}/collectionFormat_get_query']();

export const zTypesPath = z['paths_/api/v{api-version}/types_get_path']();

export const zTypesQuery = z['paths_/api/v{api-version}/types_get_query']();

export const zTypesResponse = z['paths_/api/v{api-version}/types_get_responses']();

export const zComplexTypesQuery = z['paths_/api/v{api-version}/complex_get_query']();

/**
 * Successful response
 */
export const zComplexTypesResponse = z['paths_/api/v{api-version}/complex_get_responses']();

export const zTestErrorCodeQuery = z['paths_/api/v{api-version}/error_post_query']();

export const zNonAsciiæøåÆøÅöôêÊ字符串Query = z['paths_/api/v{api-version}/non-ascii-æøåÆØÅöôêÊ字符串_post_query']();

/**
 * Successful response
 */
export const zNonAsciiæøåÆøÅöôêÊ字符串Response = zNonAsciiStringæøåÆøÅöôêÊ字符串;

/**
 * Body should not be unknown
 */
export const zPostApiVbyApiVersionBodyBody = zParameterActivityParams;

/**
 * OK
 */
export const zPostApiVbyApiVersionBodyResponse = zResponsePostActivityResponse;
