// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

export const zFoo = z.nullable(z.enum(['foo', 'bar']));

export const zBar = z.enum(['foo', 'bar']);

export const zBaz = z.nullable(z.enum(['foo', 'bar']));

export const zQux = z.object({
  value: z.nullish(z.enum(['foo', 'bar']))
});
