// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zExampleRequest = z.object({
  options: z.any().check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length >= 1)).check(z.refine(value => typeof value === 'object' && value !== null && Object.keys(value).length <= 3)).pipe(z.object({
    optionA: z.boolean().optional(),
    optionB: z.boolean().optional(),
    optionC: z.boolean().optional(),
    optionD: z.boolean().optional()
  }))
});
