// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export enum Zone {
  ETC_GMT_1 = 'Etc/GMT+1',
  ETC_GMT_12 = 'Etc/GMT+12',
  ETC_GMT_13 = 'Etc/GMT-1'
}
