// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from 'effect/Schema';

import type { RecursiveBinary } from './types.gen';

export const FilterSchema = Schema.Struct({
  role: Schema.optionalKey(Schema.String)
});

export const DictionaryWithStringSchema = Schema.Record(Schema.String, Schema.String);

export const DictionaryWithPropertiesAndAdditionalPropertiesSchema = Schema.StructWithRest(Schema.Struct({
  foo: Schema.optionalKey(Schema.Number.check(Schema.isFinite())),
  bar: Schema.optionalKey(Schema.Boolean)
}), [Schema.Record(Schema.String.check(Schema.isPattern(new RegExp('^(?!(?:foo|bar)$)[\\s\\S]*$'))), Schema.String)]);

export const FileSchema = Schema.Struct({
  mime: Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(24)),
  file: Schema.optionalKey(Schema.String.check(Schema.makeFilter(value => URL.canParse(value), { expected: 'a valid URL' })).annotate({ format: 'uri' }))
});

export const ModelWithPatternSchema = Schema.Struct({
  key: Schema.String.check(Schema.isMaxLength(64), Schema.isPattern(new RegExp('^[a-zA-Z0-9_]*$'))),
  name: Schema.String.check(Schema.isMaxLength(255)),
  modified: Schema.optionalKey(Schema.String.check(Schema.makeFilter(value => {
    if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
      return false;
    }
    if (!value.includes(':60')) {
      return true;
    }
    const parsed = new globalThis.Date(value.replace(':60', ':59'));
    if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
      return false;
    }
    return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
  }, { expected: 'an RFC 3339 date-time' })).annotate({ format: 'date-time' }))
});

export const TimeFormatsSchema = Schema.Struct({
  dateTime: Schema.String.check(Schema.makeFilter(value => {
    if (!/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))[tT](?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
      return false;
    }
    if (!value.includes(':60')) {
      return true;
    }
    const parsed = new globalThis.Date(value.replace(':60', ':59'));
    if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
      return false;
    }
    return parsed.getUTCMonth() === 5 && parsed.getUTCDate() === 30 || parsed.getUTCMonth() === 11 && parsed.getUTCDate() === 31;
  }, { expected: 'an RFC 3339 date-time' })).annotate({ format: 'date-time' }),
  time: Schema.String.check(Schema.makeFilter(value => {
    if (!/^(?:[01]\d|2[0-3]):[0-5]\d:(?:[0-5]\d|60)(?:\.\d+)?(?:[zZ]|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)) {
      return false;
    }
    if (!value.includes(':60')) {
      return true;
    }
    const parsed = new globalThis.Date('2000-01-01T' + value.replace(':60', ':59'));
    if (parsed.getUTCHours() !== 23 || parsed.getUTCMinutes() !== 59) {
      return false;
    }
    return true;
  }, { expected: 'an RFC 3339 time' })).annotate({ format: 'time' })
});

export const ClosedObjectSchema = Schema.Struct({
  known: Schema.optionalKey(Schema.String)
});

export const ClosedBaseSchema = Schema.Struct({
  a: Schema.String
});

export const ClosedIntersectionSchema = Schema.Struct({
  a: Schema.String,
  b: Schema.String
});

export const OpenPartSchema = Schema.Struct({
  a: Schema.optionalKey(Schema.String)
});

export const ClosedPartSchema = Schema.Struct({
  a: Schema.String
});

export const ReversedClosedIntersectionSchema = Schema.Struct({
  a: Schema.String
});

type EffectSchemaType<Value> = Value extends Blob ? Uint8Array : Value extends ReadonlyArray<unknown> | Record<string, unknown> ? {
  [Key in keyof Value]: EffectSchemaType<Value[Key]>;
} : Value;

export const RecursiveBinarySchema = Schema.Struct({
  file: Schema.Uint8Array,
  next: Schema.optionalKey(Schema.suspend((): Schema.Codec<EffectSchemaType<RecursiveBinary>> => RecursiveBinarySchema))
});

export const ConstrainedUnionSchema = Schema.Union([Schema.Literal('x'), Schema.Literal('long')]).check(Schema.isMinLength(3));

export const ConstrainedConstSchema = Schema.Literal('x').check(Schema.isMinLength(3));

export const ConstrainedEnumSchema = Schema.Union([Schema.Literal('x'), Schema.Literal('long')]).check(Schema.isMinLength(3));

export const ConstrainedIntersectionSchema = Schema.String.check(Schema.isMinLength(2)).check(Schema.makeFilter(Schema.is(Schema.String.check(Schema.isPattern(new RegExp('^a')))), { expected: 'a value matching this allOf member' }));

export const NestedDictionarySchema = Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.Record(Schema.String, Schema.String))))))));

export const TaggedDefaultDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const TaggedDefaultResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const UntaggedDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const UntaggedResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const ThenDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const ThenResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const ConstructorDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const ConstructorResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const ProtoDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const ProtoResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const TaggedCollisionDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const TaggedCollisionResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const ColonPathDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.Struct({
    id: Schema.String
  }),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const ColonPathResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const FileResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.Struct({
    'api-version': Schema.String,
    id: Schema.String
  }),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Audio response
 */
export const FileResponseResponseSchema = Schema.Uint8Array.annotate({ description: 'Audio response' });

export const MultipartResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Multipart response
 */
export const MultipartResponseResponseSchema = Schema.Struct({
  value: Schema.optionalKey(Schema.String)
}).annotate({ description: 'Multipart response' });

export const ImageResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const AudioResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const VideoResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const TextResponseDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

export const EventStreamDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * Server-sent events
 */
export const EventStreamResponseSchema = Schema.String.annotate({ description: 'Server-sent events' });

export const ObjectFilterDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Struct({
    filter: Schema.optionalKey(FilterSchema)
  }))
});

/**
 * No content
 */
export const ObjectFilterResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const TraceRequestDataSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.Never),
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const TraceRequestResponseSchema = Schema.Void.annotate({ description: 'No content' });

const RecursiveBinaryFileInputSchema = Schema.Struct({
  file: Schema.instanceOf(globalThis.Blob),
  next: Schema.optionalKey(Schema.suspend((): Schema.Codec<RecursiveBinary> => RecursiveBinaryFileInputSchema))
});

export const RecursiveUploadDataSchema = Schema.Struct({
  body: RecursiveBinaryFileInputSchema,
  path: Schema.optionalKey(Schema.Never),
  query: Schema.optionalKey(Schema.Never)
});

/**
 * No content
 */
export const RecursiveUploadResponseSchema = Schema.Void.annotate({ description: 'No content' });

export const ColonPathPathParamsSchema = Schema.Struct({
  id: Schema.String
});

export const ObjectFilterQuerySchema = Schema.Struct({
  filter: Schema.optionalKey(FilterSchema)
});

export const RecursiveUploadPayloadSchema = RecursiveBinarySchema;

export const FileResponsePathParamsSchema = Schema.Struct({
  api_version: Schema.String,
  id: Schema.String
});

/**
 * Audio response
 */
export const FileResponseResponse200Schema = Schema.Uint8Array.annotate({ description: 'Audio response' });
