// This file is auto-generated by @hey-api/openapi-ts

import type * as Effect from 'effect/Effect';
import * as Schema from 'effect/Schema';
import { HttpClient, HttpClientRequest } from 'effect/unstable/http';
import { HttpApi, HttpApiClient, HttpApiEndpoint, HttpApiGroup, HttpApiSchema } from 'effect/unstable/httpapi';

import { ColonPathPathParamsSchema, FileResponsePathParamsSchema, FileResponseResponse200Schema, ObjectFilterQuerySchema, RecursiveUploadPayloadSchema } from './effect-schema.gen';

const DefaultGroup = HttpApiGroup.make('default').add(HttpApiEndpoint.get('taggedDefault', '/tagged', {
  success: HttpApiSchema.Empty(204)
}));

const Default2Group = HttpApiGroup.make('default_2').add(HttpApiEndpoint.get('untagged', '/untagged', {
  success: HttpApiSchema.Empty(204)
}), HttpApiEndpoint.get('then_', '/then', {
  success: HttpApiSchema.Empty(204)
}), HttpApiEndpoint.get('colonPath', '/literal%3acolon/:id', {
  params: ColonPathPathParamsSchema,
  success: HttpApiSchema.Empty(204)
}), HttpApiEndpoint.get('objectFilter', '/filter', {
  query: ObjectFilterQuerySchema,
  success: HttpApiSchema.Empty(204)
}), HttpApiEndpoint.post('recursiveUpload', '/recursive-upload', {
  payload: RecursiveUploadPayloadSchema.pipe(HttpApiSchema.asMultipart()),
  success: HttpApiSchema.Empty(204)
}));

const PetStoreGroup = HttpApiGroup.make('petStore').add(HttpApiEndpoint.get('constructor_', '/constructor', {
  success: HttpApiSchema.Empty(204)
}), HttpApiEndpoint.get('proto', '/proto', {
  success: HttpApiSchema.Empty(204)
}));

const UntaggedGroup = HttpApiGroup.make('untagged').add(HttpApiEndpoint.get('taggedCollision', '/tagged-collision', {
  success: HttpApiSchema.Empty(204)
}));

const FilesGroup = HttpApiGroup.make('files').add(HttpApiEndpoint.get('fileResponse', '/api/v:api_version/file/:id', {
  params: FileResponsePathParamsSchema,
  success: FileResponseResponse200Schema.pipe(HttpApiSchema.asUint8Array({ contentType: 'audio/mpeg' })).pipe(HttpApiSchema.status(200))
}));

const MultipartGroup = HttpApiGroup.make('multipart').add(HttpApiEndpoint.get('multipartResponse', '/multipart-response', {
  success: Schema.Uint8Array.pipe(HttpApiSchema.asUint8Array({ contentType: 'multipart/form-data' })).pipe(HttpApiSchema.status(200))
}));

const BinaryGroup = HttpApiGroup.make('binary').add(HttpApiEndpoint.get('imageResponse', '/image', {
  success: Schema.Uint8Array.pipe(HttpApiSchema.asUint8Array({ contentType: 'image/png' })).pipe(HttpApiSchema.status(200))
}), HttpApiEndpoint.get('audioResponse', '/audio', {
  success: Schema.Uint8Array.pipe(HttpApiSchema.asUint8Array({ contentType: 'audio/ogg' })).pipe(HttpApiSchema.status(200))
}), HttpApiEndpoint.get('videoResponse', '/video', {
  success: Schema.Uint8Array.pipe(HttpApiSchema.asUint8Array({ contentType: 'video/webm' })).pipe(HttpApiSchema.status(200))
}));

const TextGroup = HttpApiGroup.make('text').add(HttpApiEndpoint.get('textResponse', '/text', {
  success: Schema.String.pipe(HttpApiSchema.asText()).pipe(HttpApiSchema.status(200))
}));

const EventsGroup = HttpApiGroup.make('events').add(HttpApiEndpoint.get('eventStream', '/events', {
  success: Schema.String.pipe(HttpApiSchema.asText({ contentType: 'text/event-stream' })).pipe(HttpApiSchema.status(200))
}));

const TraceGroup = HttpApiGroup.make('trace').add(HttpApiEndpoint.make('TRACE')('traceRequest', '/trace', {
  success: HttpApiSchema.Empty(204)
}));

export const Api = HttpApi.make('Api').add(DefaultGroup, Default2Group, PetStoreGroup, UntaggedGroup, FilesGroup, MultipartGroup, BinaryGroup, TextGroup, EventsGroup, TraceGroup);

/**
 * Restores literal colons in generated paths after Effect expands path parameters. Parameter values are encoded before the lowercase `%3a` marker is replaced.
 */
export function makeClient(options?: {
  readonly baseUrl?: URL | string | undefined;
  readonly transformClient?: ((client: HttpClient.HttpClient) => HttpClient.HttpClient) | undefined;
  readonly transformResponse?: ((effect: Effect.Effect<unknown, unknown, unknown>) => Effect.Effect<unknown, unknown, unknown>) | undefined;
}) {
  return HttpApiClient.make(Api, { ...options, transformClient: client => HttpClient.mapRequest(options?.transformClient ? options.transformClient(client) : client, request => HttpClientRequest.setUrl(request, request.url.replaceAll('%3a', ':'))) });
}
