// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Filter = {
  role?: string;
};

export type DictionaryWithString = {
  [key: string]: string;
};

export type DictionaryWithPropertiesAndAdditionalProperties = {
  foo?: number;
  bar?: boolean;
  [key: string]: string | number | boolean | undefined;
};

export type File = {
  mime: string;
  file?: string;
};

export type ModelWithPattern = {
  key: string;
  name: string;
  modified?: string;
};

export type TimeFormats = {
  dateTime: string;
  time: string;
};

export type ClosedObject = {
  known?: string;
};

export type ClosedBase = {
  a: string;
};

export type ClosedIntersection = ClosedBase & {
  b: string;
};

export type OpenPart = {
  a?: string;
};

export type ClosedPart = {
  a: string;
};

export type ReversedClosedIntersection = OpenPart & ClosedPart;

export type RecursiveBinary = {
  file: Blob | File;
  next?: RecursiveBinary;
};

export type ConstrainedUnion = 'x' | 'long';

export type ConstrainedConst = 'x';

export type ConstrainedEnum = 'x' | 'long';

export type ConstrainedIntersection = string & string;

export type NestedDictionary = {
  [key: string]: {
    [key: string]: {
      [key: string]: {
        [key: string]: {
          [key: string]: {
            [key: string]: {
              [key: string]: {
                [key: string]: string;
              };
            };
          };
        };
      };
    };
  };
};

export type TaggedDefaultData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/tagged';
};

export type TaggedDefaultResponses = {
  /**
   * No content
   */
  204: void;
};

export type TaggedDefaultResponse = TaggedDefaultResponses[keyof TaggedDefaultResponses];

export type UntaggedData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/untagged';
};

export type UntaggedResponses = {
  /**
   * No content
   */
  204: void;
};

export type UntaggedResponse = UntaggedResponses[keyof UntaggedResponses];

export type ThenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/then';
};

export type ThenResponses = {
  /**
   * No content
   */
  204: void;
};

export type ThenResponse = ThenResponses[keyof ThenResponses];

export type ConstructorData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/constructor';
};

export type ConstructorResponses = {
  /**
   * No content
   */
  204: void;
};

export type ConstructorResponse = ConstructorResponses[keyof ConstructorResponses];

export type ProtoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/proto';
};

export type ProtoResponses = {
  /**
   * No content
   */
  204: void;
};

export type ProtoResponse = ProtoResponses[keyof ProtoResponses];

export type TaggedCollisionData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/tagged-collision';
};

export type TaggedCollisionResponses = {
  /**
   * No content
   */
  204: void;
};

export type TaggedCollisionResponse = TaggedCollisionResponses[keyof TaggedCollisionResponses];

export type ColonPathData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/literal:colon/{id}';
};

export type ColonPathResponses = {
  /**
   * No content
   */
  204: void;
};

export type ColonPathResponse = ColonPathResponses[keyof ColonPathResponses];

export type FileResponseData = {
  body?: never;
  path: {
    'api-version': string;
    id: string;
  };
  query?: never;
  url: '/api/v{api-version}/file/{id}';
};

export type FileResponseResponses = {
  /**
   * Audio response
   */
  200: Blob | File;
};

export type FileResponseResponse = FileResponseResponses[keyof FileResponseResponses];

export type MultipartResponseData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/multipart-response';
};

export type MultipartResponseResponses = {
  /**
   * Multipart response
   */
  200: {
    value?: string;
  };
};

export type MultipartResponseResponse = MultipartResponseResponses[keyof MultipartResponseResponses];

export type ImageResponseData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/image';
};

export type ImageResponseResponses = {
  /**
   * Image response
   */
  200: unknown;
};

export type AudioResponseData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/audio';
};

export type AudioResponseResponses = {
  /**
   * Audio response
   */
  200: unknown;
};

export type VideoResponseData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/video';
};

export type VideoResponseResponses = {
  /**
   * Video response
   */
  200: unknown;
};

export type TextResponseData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/text';
};

export type TextResponseResponses = {
  /**
   * Text response
   */
  200: unknown;
};

export type EventStreamData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/events';
};

export type EventStreamResponses = {
  /**
   * Server-sent events
   */
  200: string;
};

export type EventStreamResponse = EventStreamResponses[keyof EventStreamResponses];

export type ObjectFilterData = {
  body?: never;
  path?: never;
  query?: {
    filter?: Filter;
  };
  url: '/filter';
};

export type ObjectFilterResponses = {
  /**
   * No content
   */
  204: void;
};

export type ObjectFilterResponse = ObjectFilterResponses[keyof ObjectFilterResponses];

export type TraceRequestData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/trace';
};

export type TraceRequestResponses = {
  /**
   * No content
   */
  204: void;
};

export type TraceRequestResponse = TraceRequestResponses[keyof TraceRequestResponses];

export type RecursiveUploadData = {
  body: RecursiveBinary;
  path?: never;
  query?: never;
  url: '/recursive-upload';
};

export type RecursiveUploadResponses = {
  /**
   * No content
   */
  204: void;
};

export type RecursiveUploadResponse = RecursiveUploadResponses[keyof RecursiveUploadResponses];
