// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Record = {
  name?: string;
  items?: Array<string>;
};

export type GetStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/status';
};

export type GetStatusResponses = {
  /**
   * Status text
   */
  200: string;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type DeleteRecordsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/records';
};

export type DeleteRecordsResponses = {
  /**
   * Records deleted
   */
  204: void;
};

export type DeleteRecordsResponse = DeleteRecordsResponses[keyof DeleteRecordsResponses];

export type GetRecordsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/records';
};

export type GetRecordsErrors = {
  /**
   * Invalid request
   */
  400: {
    message: string;
    code?: string;
  };
};

export type GetRecordsError = GetRecordsErrors[keyof GetRecordsErrors];

export type GetRecordsResponses = {
  /**
   * Existing record
   */
  200: Record & {
    kind: 'existing';
  };
  /**
   * Created record
   */
  201: Record & {
    kind: 'created';
  };
};

export type GetRecordsResponse = GetRecordsResponses[keyof GetRecordsResponses];
