// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Document = {
  id?: string;
  name?: string;
};

export type CreateDocumentData = {
  body: string;
  path?: never;
  query?: never;
  url: '/documents';
};

export type CreateDocumentResponses = {
  /**
   * OK
   */
  200: string;
};

export type CreateDocumentResponse = CreateDocumentResponses[keyof CreateDocumentResponses];
