# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, Field


class GetThingHeaders(BaseModel):
    x_request_id: str = Field(..., alias="X-Request-Id")


class GetThingPath(BaseModel):
    thing_id: str = Field(..., alias="thing-id")


class GetThingQuery(BaseModel):
    sort_by: Optional[str] = Field(default=None, alias="sort-by")
    sort_by_: Optional[str] = Field(default=None, alias="sort_by")
    from_: Optional[str] = Field(default=None, alias="from")
    _2fa: Optional[bool] = Field(default=None, alias="2fa")
