# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client


class Sdk(Client):
    def get_thing(
        self,
        x_request_id: str,
        thing_id: str,
        sort_by: Optional[str] = None,
        sort_by_: Optional[str] = None,
        from_: Optional[str] = None,
        _2fa: Optional[bool] = None,
    ) -> None:
        params = build_client_params([{"in": "headers", "key": "x_request_id", "map": "X-Request-Id"}, {"in": "path", "key": "thing_id", "map": "thing-id"}, {"in": "query", "key": "sort_by", "map": "sort-by"}, {"in": "query", "key": "sort_by_", "map": "sort_by"}, {"in": "query", "key": "from_", "map": "from"}, {"in": "query", "key": "_2fa", "map": "2fa"}], x_request_id=x_request_id, thing_id=thing_id, sort_by=sort_by, sort_by_=sort_by_, from_=from_, _2fa=_2fa)
        self.request_options("get", "/things/{thing-id}", params)
        return None
