# This file is auto-generated by @hey-api/openapi-python

from typing import Any, Optional

from pydantic import BaseModel, RootModel


class BinaryImage(RootModel[bytes]):
    root: bytes


class Tags(RootModel[list[str]]):
    root: list[str]


class UploadMetadata(BaseModel):
    label: str


class ImageUpload(BaseModel):
    image: bytes
    caption: Optional[str] = None


class UploadImageBody(BaseModel):
    image: bytes
    caption: Optional[str] = None


class UploadImageResponse(RootModel[None]):
    """Uploaded"""

    root: None


class UploadImageRefBody(RootModel[ImageUpload]):
    root: ImageUpload


class UploadImageRefResponse(RootModel[None]):
    """Uploaded"""

    root: None


class UploadImagesBody(BaseModel):
    images: list[BinaryImage]
    caption: Optional[str] = None


class UploadImagesResponse(RootModel[None]):
    """Uploaded"""

    root: None


class UploadFieldsBody(BaseModel):
    count: int
    enabled: bool
    metadata: UploadMetadata
    options: dict[str, Any]
    tags: list[str]
    counts: list[int]
    flags: list[bool]
    records: list[dict[str, Any]]
    labels: Optional[Tags] = None


class UploadFieldsResponse(RootModel[None]):
    """Sent"""

    root: None
