# This file is auto-generated by @hey-api/openapi-python

from typing import Any, Optional

from .client import build_client_params, Client
from .pydantic_gen import Tags, UploadMetadata


class Sdk(Client):
    def upload_image(self, image: bytes, caption: Optional[str] = None):
        params = build_client_params([{"in": "multipart", "key": "image", "binary": True}, {"in": "multipart", "key": "caption"}], image=image, caption=caption)
        return self.request_options("post", "/images", params)

    def upload_image_ref(self, image: bytes, caption: Optional[str] = None):
        params = build_client_params([{"in": "multipart", "key": "image", "binary": True}, {"in": "multipart", "key": "caption"}], image=image, caption=caption)
        return self.request_options("post", "/images/ref", params)

    def upload_images(self, images: list[bytes], caption: Optional[str] = None):
        params = build_client_params([{"in": "multipart", "key": "images", "array": True, "binary": True}, {"in": "multipart", "key": "caption"}], images=images, caption=caption)
        return self.request_options("post", "/images/batch", params)

    def upload_fields(
        self,
        count: int,
        enabled: bool,
        metadata: UploadMetadata,
        options: dict[str, Any],
        tags: list[str],
        counts: list[int],
        flags: list[bool],
        records: list[dict[str, Any]],
        labels: Optional[Tags] = None,
    ):
        params = build_client_params([{"in": "multipart", "key": "count"}, {"in": "multipart", "key": "enabled"}, {"in": "multipart", "key": "metadata"}, {"in": "multipart", "key": "options"}, {"in": "multipart", "key": "tags", "array": True}, {"in": "multipart", "key": "counts", "array": True}, {"in": "multipart", "key": "flags", "array": True}, {"in": "multipart", "key": "records", "array": True}, {"in": "multipart", "key": "labels", "array": True}], count=count, enabled=enabled, metadata=metadata, options=options, tags=tags, counts=counts, flags=flags, records=records, labels=labels)
        return self.request_options("post", "/fields", params)
