// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Bar = {
  id: string;
};

export type Foo = {
  sibling: Bar | null;
  wrapped: Bar | null;
  plain?: Bar;
};
