// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type MyOperations = {
  getPing: {
    data: GetPingData;
    errors: GetPingErrors;
    responses: GetPingResponses;
  };
  postPing: {
    data: PostPingData;
    responses: PostPingResponses;
  };
};

export type GetPingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/ping';
};

export type GetPingErrors = {
  /**
   * Error
   */
  '4XX': {
    message?: string;
  };
};

export type GetPingError = GetPingErrors[keyof GetPingErrors];

export type GetPingResponses = {
  /**
   * OK
   */
  200: {
    pong?: string;
  };
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type PostPingData = {
  body: string;
  path?: never;
  query?: never;
  url: '/ping';
};

export type PostPingResponses = {
  /**
   * OK
   */
  200: {
    pong?: string;
  };
};

export type PostPingResponse = PostPingResponses[keyof PostPingResponses];
