// This file is auto-generated by @hey-api/openapi-ts

import * as Data from 'effect/Data';
import type * as Effect from 'effect/Effect';
import type * as Stream from 'effect/Stream';
import type * as Sse from 'effect/unstable/encoding/Sse';
import type * as HttpClient from 'effect/unstable/http/HttpClient';
import type * as HttpClientError from 'effect/unstable/http/HttpClientError';
import type * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest';
import type * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse';

import type { Auth } from '../core/auth.gen';
import type { Client as CoreClient, Config as CoreConfig } from '../core/types.gen';

export type ResponseStyle = 'data' | 'fields';

export class ClientError extends Data.TaggedError('ClientError')<{
  readonly cause: unknown;
  readonly message: string;
  readonly stage: 'auth' | 'request' | 'response';
}> {}

export class ResponseError<T = unknown> extends Data.TaggedError('ResponseError')<{
  readonly data: T;
  readonly request: HttpClientRequest.HttpClientRequest;
  readonly response: HttpClientResponse.HttpClientResponse;
}> {}

export interface Config<T extends ClientOptions = ClientOptions> extends CoreConfig {
  /**
   * Base URL for all requests made by this client.
   */
  baseUrl?: T['baseUrl'];
  /**
   * Return response data parsed in a specified format.
   *
   * @default 'auto'
   */
  parseAs?: 'arrayBuffer' | 'auto' | 'blob' | 'formData' | 'json' | 'stream' | 'text';
  /**
   * Return only data or the data together with the Effect HTTP request and response.
   *
   * @default 'fields'
   */
  responseStyle?: ResponseStyle;
  /**
   * Transform the Effect HTTP client before a request is executed.
   */
  transformClient?: (client: HttpClient.HttpClient) => HttpClient.HttpClient;
}

export interface RequestOptions<
  _TData = unknown,
  TResponseStyle extends ResponseStyle = 'fields',
  Url extends string = string,
> extends Config<{ responseStyle: TResponseStyle }> {
  body?: unknown;
  path?: Record<string, unknown>;
  query?: Record<string, unknown>;
  /**
   * Security mechanism(s) to use for the request.
   */
  security?: ReadonlyArray<Auth>;
  url: Url;
}

export interface ResolvedRequestOptions<
  TResponseStyle extends ResponseStyle = 'fields',
  Url extends string = string,
> extends RequestOptions<unknown, TResponseStyle, Url> {
  headers: Headers;
  serializedBody?: unknown;
}

type Payload<T> = T extends Record<string, unknown> ? T[keyof T] : T;

export type RequestResult<
  TData = unknown,
  TError = unknown,
  TResponseStyle extends ResponseStyle = 'fields',
> = Effect.Effect<
  TResponseStyle extends 'data'
    ? Payload<TData>
    : {
        data: Payload<TData>;
        request: HttpClientRequest.HttpClientRequest;
        response: HttpClientResponse.HttpClientResponse;
      },
  ClientError | HttpClientError.HttpClientError | ResponseError<Payload<TError>>,
  HttpClient.HttpClient
>;

export type ServerSentEventsResult<TData = unknown, TError = unknown> = Stream.Stream<
  Payload<TData>,
  ClientError | HttpClientError.HttpClientError | ResponseError<Payload<TError>> | Sse.Retry,
  HttpClient.HttpClient
>;

export interface ClientOptions {
  baseUrl?: string;
  responseStyle?: ResponseStyle;
}

type MethodFn = <
  TData = unknown,
  TError = unknown,
  TResponseStyle extends ResponseStyle = 'fields',
>(
  options: Omit<RequestOptions<TData, TResponseStyle>, 'method'>,
) => RequestResult<TData, TError, TResponseStyle>;

type SseFn = <TData = unknown, TError = unknown>(
  options: Omit<RequestOptions<never>, 'method'>,
) => ServerSentEventsResult<TData, TError>;

type RequestFn = <
  TData = unknown,
  TError = unknown,
  TResponseStyle extends ResponseStyle = 'fields',
>(
  options: Omit<RequestOptions<TData, TResponseStyle>, 'method'> &
    Pick<Required<RequestOptions<TData, TResponseStyle>>, 'method'>,
) => RequestResult<TData, TError, TResponseStyle>;

type BuildUrlFn = <
  TData extends {
    body?: unknown;
    path?: Record<string, unknown>;
    query?: Record<string, unknown>;
    url: string;
  },
>(
  options: TData & Options<TData>,
) => string;

export type Client = CoreClient<RequestFn, Config, MethodFn, BuildUrlFn, SseFn>;

export type CreateClientConfig<T extends ClientOptions = ClientOptions> = (
  override?: Config<ClientOptions & T>,
) => Config<Required<ClientOptions> & T>;

export interface TDataShape {
  body?: unknown;
  headers?: unknown;
  path?: unknown;
  query?: unknown;
  url: string;
}

type OmitKeys<T, K> = Pick<T, Exclude<keyof T, K>>;

export type Options<
  TData extends TDataShape = TDataShape,
  TResponse = unknown,
  TResponseStyle extends ResponseStyle = 'fields',
> = OmitKeys<RequestOptions<TResponse, TResponseStyle>, 'body' | 'path' | 'query' | 'url'> &
  ([TData] extends [never] ? unknown : Omit<TData, 'url'>);
