// This file is auto-generated by @hey-api/openapi-ts

import { getAuthToken } from '../core/auth.gen';
import type { QuerySerializerOptions } from '../core/bodySerializer.gen';
import { jsonBodySerializer } from '../core/bodySerializer.gen';
import {
  serializeArrayParam,
  serializeObjectParam,
  serializePrimitiveParam,
} from '../core/pathSerializer.gen';
import { getUrl } from '../core/utils.gen';
import type { Client, ClientOptions, Config, RequestOptions } from './types.gen';

export const createQuerySerializer = <T = unknown>({
  parameters = {},
  ...args
}: QuerySerializerOptions = {}): ((queryParams: T) => string) => {
  const querySerializer = (queryParams: T): string => {
    const search: string[] = [];
    if (queryParams && typeof queryParams === 'object') {
      for (const name in queryParams) {
        const value = queryParams[name];
        if (value === undefined || value === null) continue;

        const options = parameters[name] || args;
        if (Array.isArray(value)) {
          const serialized = serializeArrayParam({
            allowReserved: options.allowReserved,
            explode: true,
            name,
            style: 'form',
            value,
            ...options.array,
          });
          if (serialized) search.push(serialized);
        } else if (typeof value === 'object') {
          const serialized = serializeObjectParam({
            allowReserved: options.allowReserved,
            explode: true,
            name,
            style: 'deepObject',
            value: value as Record<string, unknown>,
            ...options.object,
          });
          if (serialized) search.push(serialized);
        } else {
          const serialized = serializePrimitiveParam({
            allowReserved: options.allowReserved,
            name,
            value: value as string,
          });
          if (serialized) search.push(serialized);
        }
      }
    }
    return search.join('&');
  };
  return querySerializer;
};

export const getParseAs = (contentType: string | undefined): Exclude<Config['parseAs'], 'auto'> => {
  if (!contentType) return 'stream';
  const cleanContent = contentType.split(';')[0]?.trim();
  if (!cleanContent) return;
  if (cleanContent.startsWith('application/json') || cleanContent.endsWith('+json')) return 'json';
  if (cleanContent === 'multipart/form-data') return 'formData';
  if (
    ['application/', 'audio/', 'image/', 'video/'].some((type) => cleanContent.startsWith(type))
  ) {
    return 'blob';
  }
  if (cleanContent.startsWith('text/')) return 'text';
  return;
};

const checkForExistence = (
  options: Pick<RequestOptions, 'auth' | 'query'> & { headers: Headers },
  name?: string,
): boolean => {
  if (!name) return false;
  return Boolean(
    options.headers.has(name) ||
    options.query?.[name] ||
    options.headers.get('Cookie')?.includes(`${name}=`),
  );
};

export async function setAuthParams(
  options: Pick<RequestOptions, 'auth' | 'query' | 'security'> & { headers: Headers },
): Promise<void> {
  for (const auth of options.security ?? []) {
    if (checkForExistence(options, auth.name)) continue;
    const token = await getAuthToken(auth, options.auth);
    if (!token) continue;

    const name = auth.name ?? 'Authorization';
    switch (auth.in) {
      case 'query':
        options.query ??= {};
        options.query[name] = token;
        break;
      case 'cookie':
        options.headers.append('Cookie', `${name}=${token}`);
        break;
      case 'header':
      default:
        options.headers.set(name, token);
        break;
    }
  }
}

export const buildUrl: Client['buildUrl'] = (options) =>
  getUrl({
    baseUrl: options.baseUrl as string,
    path: options.path,
    query: options.query,
    querySerializer:
      typeof options.querySerializer === 'function'
        ? options.querySerializer
        : createQuerySerializer(options.querySerializer),
    url: options.url,
  });

export const mergeConfigs = (a: Config, b: Config): Config => {
  const config = { ...a, ...b };
  if (config.baseUrl?.endsWith('/')) {
    config.baseUrl = config.baseUrl.substring(0, config.baseUrl.length - 1);
  }
  config.headers = mergeHeaderValues(a.headers, b.headers);
  return config;
};

const headersEntries = (headers: Headers): Array<[string, string]> => {
  const entries: Array<[string, string]> = [];
  headers.forEach((value, key) => entries.push([key, value]));
  return entries;
};

export const mergeHeaderValues = (
  ...headers: Array<Required<Config>['headers'] | undefined>
): Record<string, unknown> => {
  const mergedHeaders: Record<string, unknown> = {};
  for (const header of headers) {
    if (!header) continue;
    const iterator = header instanceof Headers ? headersEntries(header) : Object.entries(header);
    for (const [key, value] of iterator) {
      if (value === null) {
        delete mergedHeaders[key];
      } else if (value !== undefined) {
        mergedHeaders[key] = value;
      }
    }
  }
  return mergedHeaders;
};

export const mergeHeaders = (
  ...headers: Array<Required<Config>['headers'] | undefined>
): Headers => {
  const mergedHeaders = new Headers();
  for (const [key, value] of Object.entries(mergeHeaderValues(...headers))) {
    if (Array.isArray(value)) {
      for (const item of value) mergedHeaders.append(key, item as string);
    } else {
      mergedHeaders.set(key, typeof value === 'object' ? JSON.stringify(value) : (value as string));
    }
  }
  return mergedHeaders;
};

const defaultQuerySerializer = createQuerySerializer({
  allowReserved: false,
  array: {
    explode: true,
    style: 'form',
  },
  object: {
    explode: true,
    style: 'deepObject',
  },
});

export const createConfig = <T extends ClientOptions = ClientOptions>(
  override: Config<Omit<ClientOptions, keyof T> & T> = {},
): Config<Omit<ClientOptions, keyof T> & T> => ({
  ...jsonBodySerializer,
  headers: {
    'Content-Type': 'application/json',
  },
  parseAs: 'auto',
  querySerializer: defaultQuerySerializer,
  ...override,
});
