# This file is auto-generated by @hey-api/openapi-python

from typing import Literal, Optional, Union

from pydantic import BaseModel, RootModel


class Foo(BaseModel):
    id: str


class Bar_(BaseModel):
    bar: Optional[str] = None
    id: Literal["Bar"]


class Bar(Bar_, Foo):
    pass


class Baz_(BaseModel):
    baz: Optional[str] = None
    id: Literal["Baz"]


class Baz(Baz_, Foo):
    pass


class Qux_(BaseModel):
    qux: Optional[bool] = None
    id: Literal["Qux"]


class Qux(Qux_, Foo):
    pass


class FooMapped(BaseModel):
    id: str


class BarMapped_(BaseModel):
    bar: Optional[str] = None
    id: Literal["bar"]


class BarMapped(BarMapped_, FooMapped):
    pass


class BazMapped_(BaseModel):
    baz: Optional[str] = None
    id: Literal["baz"]


class BazMapped(BazMapped_, FooMapped):
    pass


class QuxMapped_(BaseModel):
    qux: Optional[bool] = None
    id: Literal["QuxMapped"]


class QuxMapped(QuxMapped_, FooMapped):
    pass


class BarUnion(BaseModel):
    id: Optional[str] = None
    bar: Optional[str] = None


class BazUnion(BaseModel):
    id: Optional[str] = None
    baz: Optional[str] = None


class FooUnion(RootModel[Union[BarUnion, BazUnion]]):
    root: Union[BarUnion, BazUnion]


class QuxExtend(RootModel[FooUnion]):
    root: FooUnion
