# This file is auto-generated by @hey-api/openapi-python

from typing import Literal, Union

from pydantic import BaseModel, Field, RootModel


class VehicleDto(BaseModel):
    type: str = Field(..., alias="$type")
    id: int


class CarDto_(BaseModel):
    model_name: str = Field(..., alias="modelName")
    type: Literal["Car"] = Field(..., alias="$type")


class CarDto(CarDto_, VehicleDto):
    pass


class VolvoDto_(BaseModel):
    seatbelt_count: int = Field(..., alias="seatbeltCount")
    type: Literal["Volvo"] = Field(..., alias="$type")


class VolvoDto(VolvoDto_, CarDto):
    pass


class GetCarsResponse(RootModel[list[Union[CarDto, VolvoDto]]]):
    """List of cars"""

    root: list[Union[CarDto, VolvoDto]] = Field(..., description="List of cars")
