# This file is auto-generated by @hey-api/openapi-python

from typing import Any, Literal, TypeAlias, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class VehicleDto(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type: str = Field(..., alias="$type")
    id: int


class CarDto_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    model_name: str = Field(..., alias="modelName")
    type: Literal["Car"] = Field(..., alias="$type")


CarDto: TypeAlias = Any


class VolvoDto_(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    seatbelt_count: int = Field(..., alias="seatbeltCount")
    type: Literal["Volvo"] = Field(..., alias="$type")


VolvoDto: TypeAlias = Any


class GetCarsResponse(RootModel[list[Union[CarDto, VolvoDto]]]):
    """List of cars"""

    root: list[Union[CarDto, VolvoDto]] = Field(..., description="List of cars")
