// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zExampleRequest = z.object({
  options: z.object({
    optionA: z.boolean().optional(),
    optionB: z.boolean().optional()
  }).refine(value => Object.keys(value).length >= 1)
});
