# This file is auto-generated by @hey-api/openapi-python

from enum import Enum


class Reaction(str, Enum):
    VALUE_1 = "+1"
    VALUE_1_ = "-1"
    VALUE_1_10 = "1-10"
    VALUE_EMPTY = ""
    VALUE__TAG = "#tag"
    FOO_BAR = "foo@bar"
    VALUE__ = "@"
    VALUE___ = "🔥"


class Magnitude(int, Enum):
    VALUE_1e_21 = 1e+21
