# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client, Page
from .pydantic_gen import Cog, CogList, GadgetList, PulleyList, SprocketList, ThingList, Widget, WidgetList


class Sdk(Client):
    def list_widgets(self, status: Optional[str] = None, cursor: Optional[str] = None) -> Page[Widget]:
        params = build_client_params([{"in": "query", "key": "status"}, {"in": "query", "key": "cursor"}], status="status", cursor="cursor")
        response = self.client.get("/widgets", params=params)
        page = WidgetList.model_validate(response.json())
        return Page(items=page.data or [], has_more=page.has_more, fetch=self.list_widgets, kwargs={"status": status}, next_params={"cursor": page.next_cursor})

    def list_gadgets(self) -> GadgetList:
        response = self.client.get("/gadgets")
        return GadgetList.model_validate(response.json())

    def list_things(self, cursor: Optional[str] = None) -> ThingList:
        params = build_client_params([{"in": "query", "key": "cursor"}], cursor="cursor")
        response = self.client.get("/things", params=params)
        return ThingList.model_validate(response.json())

    def list_sprockets(self, cursor: str) -> SprocketList:
        params = build_client_params([{"in": "query", "key": "cursor"}], cursor="cursor")
        response = self.client.get("/sprockets", params=params)
        return SprocketList.model_validate(response.json())

    def list_cogs(self, page: Optional[int] = None, page_size: Optional[int] = None) -> Page[Cog]:
        params = build_client_params([{"in": "query", "key": "page"}, {"in": "query", "key": "page_size"}], page="page", page_size="page_size")
        response = self.client.get("/cogs", params=params)
        page_ = CogList.model_validate(response.json())
        return Page(items=page_.data or [], has_more=page_.has_more, fetch=self.list_cogs, kwargs={"page_size": page_size}, next_params={"page": (page_.page or 0) + 1})

    def list_pulleys(self, page: Optional[int] = None, page_size: Optional[int] = None) -> PulleyList:
        params = build_client_params([{"in": "query", "key": "page"}, {"in": "query", "key": "page_size"}], page="page", page_size="page_size")
        response = self.client.get("/pulleys", params=params)
        return PulleyList.model_validate(response.json())
