# This file is auto-generated by @hey-api/openapi-python

from enum import Enum
from typing import Any, Optional, TypeAlias

from pydantic import BaseModel, Field, RootModel


class Thing(BaseModel):
    name: str


Count: TypeAlias = int


class Status(str, Enum):
    DRAFT = "draft"
    LIVE = "live"


class DeleteThingPath(BaseModel):
    thing_id: str


class DeleteThingResponse(RootModel[None]):
    """No content"""

    root: None


class GetThingPath(BaseModel):
    thing_id: str


class GetThingQuery(BaseModel):
    response: Optional[str] = None


class GetThingResponse(RootModel[Thing]):
    """OK"""

    root: Thing


class GetThingPdfPath(BaseModel):
    thing_id: str


class GetThingPdfResponse(RootModel[bytes]):
    """OK"""

    root: bytes = Field(..., description="OK")


class ListThingsResponse(RootModel[list[Thing]]):
    """OK"""

    root: list[Thing] = Field(..., description="OK")


class CreateThingBody(RootModel[Thing]):
    root: Thing


class CreateThingResponse(RootModel[Thing]):
    """Created"""

    root: Thing


class CountThingsResponse(RootModel[Count]):
    """OK"""

    root: Count


class GetThingStatusPath(BaseModel):
    thing_id: str


class GetThingStatusResponse(RootModel[Status]):
    """OK"""

    root: Status


class GetThingDetailPath(BaseModel):
    thing_id: str


class GetThingDetailResponse(BaseModel):
    """OK"""

    label: str


class GetThingFullPath(BaseModel):
    thing_id: str


class GetThingFull(BaseModel):
    note: str


GetThingFullResponse: TypeAlias = Any


class GetThingNotePath(BaseModel):
    thing_id: str


class GetThingNoteResponse(RootModel[str]):
    """OK"""

    root: str = Field(..., description="OK")
