# This file is auto-generated by @hey-api/openapi-python

from .client import Client
from .pydantic_gen import CountThingsResponse, GetThingDetailResponse, GetThingNoteResponse, GetThingPdfResponse, GetThingStatusResponse, ListThingsResponse, Thing


class Sdk(Client):
    def delete_thing(self) -> None:
        self.client.delete("/things/{thing_id}")
        return None

    def get_thing(self) -> Thing:
        response = self.client.get("/things/{thing_id}")
        return Thing.model_validate(response.json())

    def get_thing_pdf(self) -> GetThingPdfResponse:
        response = self.client.get("/things/{thing_id}/pdf")
        return GetThingPdfResponse.model_validate(response.content)

    def list_things(self) -> ListThingsResponse:
        response = self.client.get("/things")
        return ListThingsResponse.model_validate(response.json())

    def create_thing(self) -> Thing:
        response = self.client.post("/things")
        return Thing.model_validate(response.json())

    def count_things(self) -> CountThingsResponse:
        response = self.client.get("/things/count")
        return CountThingsResponse.model_validate(response.json())

    def get_thing_status(self) -> GetThingStatusResponse:
        response = self.client.get("/things/{thing_id}/status")
        return GetThingStatusResponse.model_validate(response.json())

    def get_things_summary(self):
        return self.client.get("/things/summary")

    def get_things_report(self):
        return self.client.get("/things/report")

    def get_thing_detail(self) -> GetThingDetailResponse:
        response = self.client.get("/things/{thing_id}/detail")
        return GetThingDetailResponse.model_validate(response.json())

    def get_thing_full(self):
        return self.client.get("/things/{thing_id}/full")

    def get_thing_note(self) -> GetThingNoteResponse:
        response = self.client.get("/things/{thing_id}/note")
        return GetThingNoteResponse.model_validate(response.text)

    def get_thing_missing_ref(self):
        return self.client.get("/things/{thing_id}/missing")
