# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from .client import build_client_params, Client
from .pydantic_gen import CountThingsResponse, GetThingDetailResponse, GetThingNoteResponse, GetThingPdfResponse, GetThingStatusResponse, ListThingsResponse, Thing


class Sdk(Client):
    def delete_thing(self, thing_id: str) -> None:
        params = build_client_params([{"in": "path", "key": "thing_id"}], thing_id=thing_id)
        self.request_options("delete", "/things/{thing_id}", params)
        return None

    def get_thing(self, thing_id: str, response: Optional[str] = None) -> Thing:
        params = build_client_params([{"in": "path", "key": "thing_id"}, {"in": "query", "key": "response"}], thing_id=thing_id, response=response)
        response_ = self.request_options("get", "/things/{thing_id}", params)
        return Thing.model_validate(response_.json())

    def get_thing_pdf(self, thing_id: str) -> GetThingPdfResponse:
        params = build_client_params([{"in": "path", "key": "thing_id"}], thing_id=thing_id)
        response = self.request_options("get", "/things/{thing_id}/pdf", params)
        return GetThingPdfResponse.model_validate(response.content)

    def list_things(self) -> ListThingsResponse:
        response = self.client.get("/things")
        return ListThingsResponse.model_validate(response.json())

    def create_thing(self, thing: Thing) -> Thing:
        params = build_client_params([{"in": "body", "key": "thing", "map": "body"}], thing=thing)
        response = self.request_options("post", "/things", params)
        return Thing.model_validate(response.json())

    def count_things(self) -> CountThingsResponse:
        response = self.client.get("/things/count")
        return CountThingsResponse.model_validate(response.json())

    def get_thing_status(self, thing_id: str) -> GetThingStatusResponse:
        params = build_client_params([{"in": "path", "key": "thing_id"}], thing_id=thing_id)
        response = self.request_options("get", "/things/{thing_id}/status", params)
        return GetThingStatusResponse.model_validate(response.json())

    def get_things_summary(self):
        return self.client.get("/things/summary")

    def get_things_report(self):
        return self.client.get("/things/report")

    def get_thing_detail(self, thing_id: str) -> GetThingDetailResponse:
        params = build_client_params([{"in": "path", "key": "thing_id"}], thing_id=thing_id)
        response = self.request_options("get", "/things/{thing_id}/detail", params)
        return GetThingDetailResponse.model_validate(response.json())

    def get_thing_full(self, thing_id: str):
        params = build_client_params([{"in": "path", "key": "thing_id"}], thing_id=thing_id)
        return self.request_options("get", "/things/{thing_id}/full", params)

    def get_thing_note(self, thing_id: str) -> GetThingNoteResponse:
        params = build_client_params([{"in": "path", "key": "thing_id"}], thing_id=thing_id)
        response = self.request_options("get", "/things/{thing_id}/note", params)
        return GetThingNoteResponse.model_validate(response.text)
