# This file is auto-generated by @hey-api/openapi-python

from typing import Optional

from pydantic import BaseModel, RootModel


class CreatePet(BaseModel):
    name: str


class GetPetPath(BaseModel):
    pet_id: str


class GetPetQuery(BaseModel):
    include_owner: Optional[bool] = None
    fields: Optional[list[str]] = None


class CreatePetBody(RootModel[CreatePet]):
    root: CreatePet
