// This file is auto-generated by @hey-api/openapi-ts

export type { BarRead, BarWrite, Baz, ClientOptions, Corge, FooRead, FooReadWrite, FooWrite, Grault, GraultAudit, GraultDetail, PostFooReadData, PostFooReadResponse, PostFooReadResponses, PostFooReadWriteData, PostFooReadWriteResponse, PostFooReadWriteResponses, PostFooWriteData, PostFooWriteResponse, PostFooWriteResponses, Quux, QuxAllRead } from './types.gen';
