# This file is auto-generated by @hey-api/openapi-python

import json
from typing import Any, Optional
from urllib.parse import quote

import httpx

EXTRA_PREFIXES_MAP = {
    "$body_": "json",
    "$headers_": "headers",
    "$path_": "path",
    "$query_": "params",
}


def build_client_params(fields: list[dict[str, Any]], /, **kwargs) -> dict[str, Any]:
    """Build client parameters from flat keyword arguments.

    Args:
        fields: List of field configurations with 'in', 'key', optional 'map', 'array' and 'binary'.
        **kwargs: Flat parameters passed to the SDK method.

    Returns:
        Dict suitable for httpx client methods, including multipart files when needed.
    """
    result: dict[str, Any] = {}

    key_map = {}
    for field in fields:
        key = field.get("key")
        if key:
            key_map[key] = {
                "in": field.get("in"),
                "map": field.get("map", key),
                "array": field.get("array", False),
                "binary": field.get("binary", False),
            }

    for key, value in kwargs.items():
        if value is None:
            continue

        field = key_map.get(key)

        if field:
            in_slot = field["in"]
            map_key = field["map"]
            if in_slot == "multipart":
                files = result.setdefault("files", [])
                if not field["binary"] and hasattr(value, "model_dump"):
                    value = value.model_dump(mode="json", by_alias=True)
                values = value if field["array"] else [value]
                for item in values:
                    if not field["binary"]:
                        if hasattr(item, "model_dump"):
                            item = item.model_dump(mode="json", by_alias=True)
                        if not isinstance(item, str):
                            item = json.dumps(item, ensure_ascii=False, separators=(",", ":"))
                    files.append((map_key, (map_key if field["binary"] else None, item)))
                continue
            slot = {"body": "json", "query": "params"}.get(in_slot, in_slot)

            if in_slot == "body" and map_key == "body":
                result[slot] = value
            else:
                if slot not in result:
                    result[slot] = {}
                result[slot][map_key] = value
        else:
            for prefix, slot in EXTRA_PREFIXES_MAP.items():
                if key.startswith(prefix):
                    actual_key = key[len(prefix) :]
                    if slot not in result:
                        result[slot] = {}
                    result[slot][actual_key] = value
                    break
            else:
                if "params" not in result:
                    result["params"] = {}
                result["params"][key] = value

    for slot in ("headers", "params", "path"):
        if slot in result and not result[slot]:
            del result[slot]

    return result


class BaseClient:
    """Base HTTP client using httpx that SDK classes extend."""

    def __init__(self, client: Optional[httpx.Client] = None, base_url: Optional[str] = None, **kwargs):
        if client is not None:
            self._client = client
        else:
            self._client = httpx.Client(base_url=base_url or "", **kwargs)

    @property
    def client(self) -> httpx.Client:
        """Get the httpx client instance."""
        return self._client

    def request(self, method: str, url: str, **kwargs) -> httpx.Response:
        """Make an HTTP request."""
        return self._client.request(method, url, **kwargs)

    def request_options(
        self,
        method: str,
        url: str,
        options: Optional[dict[str, Any]] = None,
        **kwargs,
    ) -> httpx.Response:
        """Make a request after substituting path parameters and serializing Pydantic JSON bodies."""
        request_options = dict(options or {})
        path = request_options.pop("path", {})
        for key, value in path.items():
            url = url.replace(f"{{{key}}}", quote(str(value), safe=""))

        body = request_options.get("json")
        if hasattr(body, "model_dump"):
            request_options["json"] = body.model_dump(mode="json", by_alias=True)

        return self.request(method, url, **request_options, **kwargs)

    def get(self, url: str, **kwargs) -> httpx.Response:
        """Make a GET request."""
        return self._client.get(url, **kwargs)

    def post(self, url: str, **kwargs) -> httpx.Response:
        """Make a POST request."""
        return self._client.post(url, **kwargs)

    def put(self, url: str, **kwargs) -> httpx.Response:
        """Make a PUT request."""
        return self._client.put(url, **kwargs)

    def patch(self, url: str, **kwargs) -> httpx.Response:
        """Make a PATCH request."""
        return self._client.patch(url, **kwargs)

    def delete(self, url: str, **kwargs) -> httpx.Response:
        """Make a DELETE request."""
        return self._client.delete(url, **kwargs)

    def close(self):
        """Close the client."""
        self._client.close()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()


class Client(BaseClient):
    """HTTP client using httpx (alias for BaseClient)."""

    pass


def create_client(base_url: Optional[str] = None, **kwargs) -> Client:
    """Create a new HTTP client instance."""
    return Client(base_url=base_url, **kwargs)
