// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { type Options, search } from '../sdk.gen';
import type { SearchData, SearchResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'path'> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
  QueryKey<TOptions>[0]
] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const searchQueryKey = (options: Options<SearchData>) => createQueryKey('search', options);

export const searchQuery = defineQueryOptions<Options<SearchData>, SearchResponse, Error>((options: Options<SearchData>) => ({
  key: searchQueryKey(options),
  query: async (context) => {
    const { data } = await search({
      ...options,
      ...context,
      throwOnError: true
    });
    return data;
  }
}));
